<?php return array(
    'name' => 'Yahoo Emoticons',
    'author' => 'Yahoo Inc.',
    'description' => 'A set of emoticons originally released with Yahoo Messenger during the IM boom of the 90s.',
    'format' => '<img class="emoji" src="{src}" title="{name}" alt="{name}" />',
    'icon' => 'yahoo-icon.png',
    'emoji' =>
        array(
            'angry' => 'angry.gif',
            'anguished' => 'anguished.gif',
            'bawling' => 'bawling.gif',
            'bee' => 'bee.gif',
            'blush' => 'blush.gif',
            'bow' => 'bow.gif',
            'bring_it' => 'bring_it.gif',
            'chicken' => 'chicken.gif',
            'clap' => 'clap.gif',
            'coffee' => 'coffee.gif',
            'confounded' => 'confounded.gif',
            'confused' => 'confused.gif',
            'cow' => 'cow.gif',
            'cowboy' => 'cowboy.gif',
            'cry' => 'cry.gif',
            'disappointed' => 'disappointed.gif',
            'dizzy' => 'dizzy.gif',
            'dog' => 'dog.gif',
            'fearful' => 'fearful.gif',
            'flushed' => 'flushed.gif',
            'frowning' => 'frowning.gif',
            'get_outta_here' => 'get_outta_here.gif',
            'giggle' => 'giggle.gif',
            'glasses' => 'glasses.gif',
            'grimacing' => 'grimacing.gif',
            'grin' => 'grin.gif',
            'hang_loose' => 'hang_loose.gif',
            'heart' => 'heart.gif',
            'heartbreak' => 'heartbreak.gif',
            'how_interesting' => 'how_interesting.gif',
            'hug' => 'hug.gif',
            'hushed' => 'hushed.gif',
            'i_dunno' => 'i_dunno.gif',
            'innocent' => 'innocent.gif',
            'jack_o_lantern' => 'jack_o_lantern.gif',
            'joker' => 'joker.gif',
            'joy' => 'joy.gif',
            'kiss' => 'kiss.gif',
            'liar' => 'liar.gif',
            'lightbulb' => 'lightbulb.gif',
            'lol' => 'lol.gif',
            'look_at_the_time' => 'look_at_the_time.gif',
            'loser' => 'loser.gif',
            'lucky' => 'lucky.gif',
            'minus_one' => 'minus_one.gif',
            'money' => 'money.gif',
            'monkey' => 'monkey.gif',
            'mrgreen' => 'mrgreen.gif',
            'murica' => 'murica.gif',
            'naughty' => 'naughty.gif',
            'neutral' => 'neutral.gif',
            'no_mouth' => 'no_mouth.gif',
            'not_listening' => 'not_listening.gif',
            'nuh_uh' => 'nuh_uh.gif',
            'ohstop' => 'ohstop.gif',
            'one_finger' => 'one_finger.gif',
            'open_mouth' => 'open_mouth.gif',
            'peace' => 'peace.gif',
            'pensive' => 'pensive.gif',
            'perturbed' => 'perturbed.gif',
            'pig' => 'pig.gif',
            'pirate' => 'pirate.gif',
            'plus_one' => 'plus_one.gif',
            'prayer' => 'prayer.gif',
            'punch' => 'punch.gif',
            'rage' => 'rage.gif',
            'relaxed' => 'relaxed.gif',
            'relieved' => 'relieved.gif',
            'rock_on' => 'rock_on.gif',
            'rofl' => 'rofl.gif',
            'rose' => 'rose.gif',
            'scream' => 'scream.gif',
            'sick' => 'sick.gif',
            'skull' => 'skull.gif',
            'sleeping' => 'sleeping.gif',
            'sleepy' => 'sleepy.gif',
            'smile' => 'smile.gif',
            'smiley' => 'smiley.gif',
            'smirk' => 'smirk.gif',
            'star' => 'star.gif',
            'sunglasses' => 'sunglasses.gif',
            'time_out' => 'time_out.gif',
            'tired_face' => 'tired_face.gif',
            'tongue' => 'tongue.gif',
            'transformer' => 'transformer.gif',
            'triumph' => 'triumph.gif',
            'unamused' => 'unamused.gif',
            'weary' => 'weary.gif',
            'whistle' => 'whistle.gif',
            'who_me' => 'who_me.gif',
            'wink' => 'wink.gif',
            'worried' => 'worried.gif',
            'yin_yang' => 'yin_yang.gif',
        ),
    'aliases' =>
        array(
            ':)' => 'smile',
            ':D' => 'grin',
            ';)' => 'wink',
            ':\\' => 'confused',
            ':/' => 'confused',
            ':o' => 'open_mouth',
            ':s' => 'confounded',
            ':p' => 'tongue',
            ':\'(' => 'cry',
            ':|' => 'neutral',
            'D:' => 'anguished',
            'B)' => 'sunglasses',
            'o:)' => 'innocent',
            '<3' => 'heart',
            '8-)' => 'glasses',
            '=)' => 'smiley',
            '>_<' => 'rage',
            ':3' => 'blush',
        ),
    'editor' =>
        array(
            ':)' => 'smile',
            ':D' => 'smiley',
            ';)' => 'wink',
            ':o' => 'open_mouth',
            ':s' => 'confounded',
            ':|' => 'neutral',
            'B)' => 'sunglasses',
            ':#' => 'grin',
        ),
    'archive' =>
        array(
            'broken_heart' => 'heartbreak.gif',
            'dizzy_face' => 'dizzy.gif',
            'grinning' => 'grin.gif',
            'neutral_face' => 'neutral.gif',
            'smiling_imp' => 'naughty.gif',
            'sob' => 'bawling.gif',
            'stuck_out_tongue' => 'tongue.gif',
            'stuck_out_tongue_closed_eyes' => 'stuck_out_tongue_closed_eyes.gif',
        ),
    'minSize' =>
        array(
            'w' => 17,
            'h' => 18,
        ),
    'maxSize' =>
        array(
            'w' => 52,
            'h' => 22,
        ),
    'sizes' =>
        array(
            0 => 1,
        ),
);
