codecov:
    require_ci_to_pass: true
    notify:
        wait_for_ci: true

coverage:
    precision: 2
    round: down
    range: "...90"

    status:
        project:
            default:
                informational: true
        patch:
            front-end:
                informational: true
        changes: false

parsers:
    gcov:
        branch_detection:
            conditional: yes
            loop: yes
            method: no
            macro: no

flag_management:
    individual_flags: # exceptions to the default rules above, stated flag by flag
        - name: frontend
          paths:
              - "**/*.ts"
              - "**/*.tsx"
          carryforward: true
          statuses:
              - type: project
                target: auto
              - type: patch
                target: 60%
        - name: backend
          paths:
              - "**/*.php"
          carryforward: true
          statuses:
              - type: project
                target: auto
              - type: patch
                target: 80%

comment:
    layout: "diff,flags"
    behavior: default
    require_changes: true
    show_carryforward_flags: true

ignore:
    - "**/views/**/*.php"
    - "**/settings/*.php"
    - "**/conf/**/*.php"
    - "**/*.css"
    - "**/*.scss"
    - "**/tests/**/*.php"
    - "applications/vanilla/settings/configuration.php"
    - "library/deprecated"
