nmHoistingLimits: none

nodeLinker: node-modules

plugins:
    - checksum: 0637851361d483f185e9ad1f9a103bb3232fed21b4c020fa10542a22d351c0853ade813558aa81456d800154fa7a9acaf2d68d4bb9c1d08018da42b0344dc7ed
      path: .yarn/plugins/@yarnpkg/plugin-licenses-audit.cjs
      spec: "https://raw.githubusercontent.com/tophat/yarn-plugin-licenses/master/bundles/@yarnpkg/plugin-licenses-audit.js"

yarnPath: .yarn/releases/yarn-4.1.1.cjs
