nodeLinker: node-modules

plugins:
    - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
      spec: "@yarnpkg/plugin-interactive-tools"
    - path: .yarn/plugins/@yarnpkg/plugin-licenses.cjs
      spec: "https://raw.githubusercontent.com/mhassan1/yarn-plugin-licenses/v0.7.2/bundles/@yarnpkg/plugin-licenses.js"

yarnPath: .yarn/releases/yarn-3.1.1.cjs
