<?php return array(
    'name' => 'Twitter Emoji',
    'author' => 'Twitter, Inc.',
    'description' => 'The emoji used on Twitter\'s web app. Twitter emoji for everyone.',
    'format' => '<img class="emoji" src="{src}" title="{name}" alt="{name}" height="18" />',
    'icon' => 'twitter-icon.png',
    'emoji' =>
        array(
            -1 => '-1.png',
            '+1' => '+1.png',
            'angry' => 'angry.png',
            'anguished' => 'anguished.png',
            'astonished' => 'astonished.png',
            'bawling' => 'bawling.png',
            'bleep_bloop' => 'bleep_bloop.png',
            'blush' => 'blush.png',
            'cold_sweat' => 'cold_sweat.png',
            'confounded' => 'confounded.png',
            'confused' => 'confused.png',
            'cookie' => 'cookie.png',
            'cry' => 'cry.png',
            'dissapointed' => 'dissapointed.png',
            'dissapointed_relieved' => 'dissapointed_relieved.png',
            'dizzy' => 'dizzy.png',
            'expressionless' => 'expressionless.png',
            'fearful' => 'fearful.png',
            'flushed' => 'flushed.png',
            'frown' => 'frown.png',
            'grey_question' => 'grey_question.png',
            'grimace' => 'grimace.png',
            'grin' => 'grin.png',
            'heart' => 'heart.png',
            'heartbreak' => 'heartbreak.png',
            'hushed' => 'hushed.png',
            'innocent' => 'innocent.png',
            'joy' => 'joy.png',
            'kiss' => 'kiss.png',
            'kissing_blush' => 'kissing_blush.png',
            'kissing_wink' => 'kissing_wink.png',
            'lol' => 'lol.png',
            'love' => 'love.png',
            'mask' => 'mask.png',
            'mrgreen' => 'mrgreen.png',
            'naughty' => 'naughty.png',
            'neutral' => 'neutral.png',
            'no_mouth' => 'no_mouth.png',
            'open_mouth' => 'open_mouth.png',
            'pensive' => 'pensive.png',
            'persevere' => 'persevere.png',
            'rage' => 'rage.png',
            'relaxed' => 'relaxed.png',
            'relieved' => 'relieved.png',
            'scream' => 'scream.png',
            'skull' => 'skull.png',
            'sleeping' => 'sleeping.png',
            'sleepy' => 'sleepy.png',
            'smile' => 'smile.png',
            'smiley' => 'smiley.png',
            'smirk' => 'smirk.png',
            'star' => 'star.png',
            'sunglasses' => 'sunglasses.png',
            'sweat' => 'sweat.png',
            'sweat_smile' => 'sweat_smile.png',
            'tired_face' => 'tired_face.png',
            'tongue' => 'tongue.png',
            'triumph' => 'triumph.png',
            'trollface' => 'trollface.png',
            'unamused' => 'unamused.png',
            'warning' => 'warning.png',
            'weary' => 'weary.png',
            'wink' => 'wink.png',
            'worried' => 'worried.png',
            'yum' => 'yum.png',
        ),
    'aliases' =>
        array(
            ':)' => 'smile',
            ':D' => 'grin',
            ':(' => 'frown',
            ';)' => 'wink',
            ':\\' => 'confused',
            ':/' => 'confused',
            ':o' => 'open_mouth',
            ':s' => 'confounded',
            ':p' => 'tongue',
            ':\'(' => 'cry',
            ':|' => 'neutral',
            'D:' => 'anguished',
            'B)' => 'sunglasses',
            ':#' => 'grimace',
            'o:)' => 'innocent',
            '<3' => 'heart',
            '=)' => 'smiley',
            '>_<' => 'rage',
            ':3' => 'blush',
        ),
    'editor' =>
        array(
            ':)' => 'smile',
            ':D' => 'smiley',
            ';)' => 'wink',
            ':\\' => 'confused',
            ':o' => 'open_mouth',
            ':s' => 'confounded',
            ':p' => 'tongue',
            ':\'(' => 'cry',
            'B)' => 'sunglasses',
            ':#' => 'grimace',
            ':3' => 'blush',
            '<3' => 'heart',
        ),
    'archive' =>
        array(
            'broken_heart' => 'heartbreak.png',
            'dizzy_face' => 'dizzy.png',
            'grinning' => 'grin.png',
            'heart_eyes' => 'love.png',
            'kissing_closed_eyes' => 'kissing_closed_eyes.png',
            'kissing_smiling_eyes' => 'kissing_smiling_eyes.png',
            'neutral_face' => 'neutral.png',
            'smiling_imp' => 'naughty.png',
            'sob' => 'bawling.png',
            'stuck_out_tongue' => 'tongue.png',
            'stuck_out_tongue_closed_eyes' => 'stuck_out_tongue_closed_eyes.png',
            'stuck_out_tongue_winking_eye' => 'stuck_out_tongue_winking_eye.png',
        ),
    'minSize' =>
        array(
            'w' => 36,
            'h' => 36,
        ),
    'maxSize' =>
        array(
            'w' => 40,
            'h' => 40,
        ),
    'sizes' =>
        array(
            0 => 1,
        ),
);
