<?php
/**
 * @author Todd Burry <todd@vanillaforums.com>
 * @copyright 2009-2020 Vanilla Forums Inc.
 * @license GPL-2.0-only
 */

namespace VanillaTests\Models;

use PHPUnit\Framework\TestCase;
use Vanilla\Utility\ArrayUtils;
use VanillaTests\SiteTestTrait;

class CategoryModelTest extends TestCase {
    use SiteTestTrait;

    /**
     * @var \CategoryModel
     */
    private $model;

    public function setUp(): void {
        $this->setupSiteTestTrait();
        $this->container()->call(function (
            \CategoryModel $categoryModel
        ) {
            $this->model = $categoryModel;
        });
    }

    public function sortFlatCategories(&$categories) {
        $fn = function (&$categories) {
            $this->sortFlatCategories($categories);
        };
        $sort = $fn->bindTo($this->model, $this->model);
        $sort($categories);
    }

    public function testSortFlatCategories(): void {
        $categories = $this->getCategoryFlattenData();
        $sorted = $this->getCategoryFlattenData();
        $this->sortFlatCategories($sorted);

        $this->assertSortedCategories($categories, $sorted);
    }

    public function testSortFlatCategoriesLocal(): void {
        $categories = $this->getLocalHostCategories();
        $sorted = $this->getLocalHostCategories();
        $this->sortFlatCategories($sorted);

        $this->assertSortedCategories($categories, $sorted);
    }

    public static function pruneColumns($categories) {
        foreach ($categories as &$v) {
            $v = arrayTranslate($v, ['CategoryID', 'TreeLeft', 'TreeRight', 'ParentCategoryID', 'Name', 'DisplayAs']);
        }
        return $categories;
    }

    protected function getLocalHostCategories(): array {
        $r = [
            -1 =>
                [
                    'CategoryID' => -1,
                    'ParentCategoryID' => -1,
                    'TreeLeft' => 1,
                    'TreeRight' => 42,
                    'Depth' => 0,
                    'CountCategories' => 5,
                    'CountDiscussions' => 0,
                    'CountComments' => 0,
                    'DateMarkedRead' => NULL,
                    'AllowDiscussions' => 1,
                    'Archived' => 0,
                    'CanDelete' => 1,
                    'Name' => 'Root',
                    'UrlCode' => 'root',
                    'Description' => 'Root of category tree. Users should never see this.',
                    'Sort' => 1,
                    'CssClass' => NULL,
                    'Photo' => NULL,
                    'BannerImage' => NULL,
                    'PermissionCategoryID' => -1,
                    'PointsCategoryID' => 0,
                    'HideAllDiscussions' => 0,
                    'DisplayAs' => 'Default',
                    'InsertUserID' => 1,
                    'UpdateUserID' => 1,
                    'DateInserted' => '2011-04-20 11:21:38',
                    'DateUpdated' => '2011-04-20 11:21:38',
                    'LastCommentID' => NULL,
                    'LastDiscussionID' => NULL,
                    'LastDateInserted' => NULL,
                    'AllowedDiscussionTypes' => NULL,
                    'DefaultDiscussionType' => NULL,
                    'ForeignID' => '',
                    'ImportUrlCode' => NULL,
                    'AdSite' => NULL,
                    'AdZone' => NULL,
                    'NoPanelAd1' => NULL,
                    'NoPanelAd2' => NULL,
                    'CoreMetricsName' => NULL,
                    'NoIndex' => NULL,
                    'LocalResourceBadges' => 0,
                    'Source' => '',
                    'AllowGroups' => 0,
                    'Type' => '',
                    'AllowFileUploads' => 1,
                    'ShowDescription' => 0,
                    'Label' => NULL,
                    'UseDownVotes' => NULL,
                    'IdeationType' => NULL,
                    'CountAllDiscussions' => 186,
                    'CountAllComments' => 416,
                    'LastCategoryID' => 0,
                ],
            10 =>
                [
                    'CategoryID' => 10,
                    'ParentCategoryID' => -1,
                    'TreeLeft' => 2,
                    'TreeRight' => 9,
                    'Depth' => 1,
                    'CountCategories' => 3,
                    'CountDiscussions' => 10,
                    'CountComments' => 1,
                    'DateMarkedRead' => NULL,
                    'AllowDiscussions' => 1,
                    'Archived' => 0,
                    'CanDelete' => 1,
                    'Name' => 'General',
                    'UrlCode' => 'general',
                    'Description' => '',
                    'Sort' => 2,
                    'CssClass' => 'Category-general',
                    'Photo' => NULL,
                    'BannerImage' => NULL,
                    'PermissionCategoryID' => 10,
                    'PointsCategoryID' => 0,
                    'HideAllDiscussions' => 0,
                    'DisplayAs' => 'Heading',
                    'InsertUserID' => 0,
                    'UpdateUserID' => 1,
                    'DateInserted' => '2011-10-31 22:18:53',
                    'DateUpdated' => '2011-10-31 22:18:53',
                    'LastCommentID' => NULL,
                    'LastDiscussionID' => 517033,
                    'LastDateInserted' => '2020-05-28 01:23:11',
                    'AllowedDiscussionTypes' => 'a:2:{i:0;s:10:"Discussion";i:1;s:4:"Poll";}',
                    'DefaultDiscussionType' => NULL,
                    'ForeignID' => '',
                    'ImportUrlCode' => NULL,
                    'AdSite' => NULL,
                    'AdZone' => NULL,
                    'NoPanelAd1' => NULL,
                    'NoPanelAd2' => NULL,
                    'CoreMetricsName' => NULL,
                    'NoIndex' => NULL,
                    'LocalResourceBadges' => 0,
                    'Source' => '',
                    'AllowGroups' => 0,
                    'Type' => '',
                    'AllowFileUploads' => 0,
                    'ShowDescription' => 0,
                    'Label' => NULL,
                    'UseDownVotes' => NULL,
                    'IdeationType' => NULL,
                    'CountAllDiscussions' => 37,
                    'CountAllComments' => 99,
                    'LastCategoryID' => 23,
                ],
            24 =>
                [
                    'CategoryID' => 24,
                    'ParentCategoryID' => 10,
                    'TreeLeft' => 3,
                    'TreeRight' => 4,
                    'Depth' => 2,
                    'CountCategories' => 0,
                    'CountDiscussions' => 1,
                    'CountComments' => 0,
                    'DateMarkedRead' => NULL,
                    'AllowDiscussions' => 1,
                    'Archived' => 0,
                    'CanDelete' => 1,
                    'Name' => 'Ideas',
                    'UrlCode' => 'ideas-too',
                    'Description' => '',
                    'Sort' => 3,
                    'CssClass' => '',
                    'Photo' => '',
                    'BannerImage' => NULL,
                    'PermissionCategoryID' => 10,
                    'PointsCategoryID' => 0,
                    'HideAllDiscussions' => 0,
                    'DisplayAs' => 'Discussions',
                    'InsertUserID' => 1,
                    'UpdateUserID' => 1,
                    'DateInserted' => '2018-09-20 17:59:03',
                    'DateUpdated' => '2018-09-20 17:59:03',
                    'LastCommentID' => NULL,
                    'LastDiscussionID' => 517016,
                    'LastDateInserted' => '2018-09-20 17:59:35',
                    'AllowedDiscussionTypes' => '["Idea"]',
                    'DefaultDiscussionType' => NULL,
                    'ForeignID' => NULL,
                    'ImportUrlCode' => NULL,
                    'AdSite' => NULL,
                    'AdZone' => NULL,
                    'NoPanelAd1' => NULL,
                    'NoPanelAd2' => NULL,
                    'CoreMetricsName' => NULL,
                    'NoIndex' => NULL,
                    'LocalResourceBadges' => 0,
                    'Source' => NULL,
                    'AllowGroups' => 0,
                    'Type' => NULL,
                    'AllowFileUploads' => 1,
                    'ShowDescription' => 0,
                    'Label' => NULL,
                    'UseDownVotes' => NULL,
                    'IdeationType' => 'up',
                    'CountAllDiscussions' => 1,
                    'CountAllComments' => 0,
                    'LastCategoryID' => 24,
                ],
            23 =>
                [
                    'CategoryID' => 23,
                    'ParentCategoryID' => 10,
                    'TreeLeft' => 5,
                    'TreeRight' => 6,
                    'Depth' => 2,
                    'CountCategories' => 0,
                    'CountDiscussions' => 22,
                    'CountComments' => 100,
                    'DateMarkedRead' => NULL,
                    'AllowDiscussions' => 1,
                    'Archived' => 0,
                    'CanDelete' => 1,
                    'Name' => 'Floosh',
                    'UrlCode' => 'floosh',
                    'Description' => '',
                    'Sort' => 5,
                    'CssClass' => 'Category-floosh',
                    'Photo' => '',
                    'BannerImage' => NULL,
                    'PermissionCategoryID' => 23,
                    'PointsCategoryID' => 0,
                    'HideAllDiscussions' => 0,
                    'DisplayAs' => 'Discussions',
                    'InsertUserID' => 1,
                    'UpdateUserID' => 1,
                    'DateInserted' => '2016-08-10 19:15:14',
                    'DateUpdated' => '2019-11-06 15:49:03',
                    'LastCommentID' => NULL,
                    'LastDiscussionID' => 517033,
                    'LastDateInserted' => '2020-05-28 01:23:11',
                    'AllowedDiscussionTypes' => '["Discussion","Poll"]',
                    'DefaultDiscussionType' => NULL,
                    'ForeignID' => NULL,
                    'ImportUrlCode' => NULL,
                    'AdSite' => NULL,
                    'AdZone' => NULL,
                    'NoPanelAd1' => NULL,
                    'NoPanelAd2' => NULL,
                    'CoreMetricsName' => NULL,
                    'NoIndex' => NULL,
                    'LocalResourceBadges' => 0,
                    'Source' => NULL,
                    'AllowGroups' => 0,
                    'Type' => NULL,
                    'AllowFileUploads' => 0,
                    'ShowDescription' => 0,
                    'Label' => NULL,
                    'UseDownVotes' => NULL,
                    'IdeationType' => NULL,
                    'CountAllDiscussions' => 23,
                    'CountAllComments' => 97,
                    'LastCategoryID' => 23,
                ],
            21 =>
                [
                    'CategoryID' => 21,
                    'ParentCategoryID' => 10,
                    'TreeLeft' => 7,
                    'TreeRight' => 8,
                    'Depth' => 2,
                    'CountCategories' => 0,
                    'CountDiscussions' => 2,
                    'CountComments' => 4,
                    'DateMarkedRead' => NULL,
                    'AllowDiscussions' => 1,
                    'Archived' => 0,
                    'CanDelete' => 1,
                    'Name' => 'Announcements',
                    'UrlCode' => 'announcements',
                    'Description' => '',
                    'Sort' => 7,
                    'CssClass' => '',
                    'Photo' => NULL,
                    'BannerImage' => NULL,
                    'PermissionCategoryID' => 10,
                    'PointsCategoryID' => 0,
                    'HideAllDiscussions' => 0,
                    'DisplayAs' => 'Default',
                    'InsertUserID' => 74262,
                    'UpdateUserID' => 1,
                    'DateInserted' => '2014-12-22 21:06:47',
                    'DateUpdated' => '2016-05-07 15:26:52',
                    'LastCommentID' => 370327,
                    'LastDiscussionID' => 517002,
                    'LastDateInserted' => '2017-02-28 21:23:18',
                    'AllowedDiscussionTypes' => 'a:2:{i:0;s:10:"Discussion";i:1;s:4:"Poll";}',
                    'DefaultDiscussionType' => NULL,
                    'ForeignID' => NULL,
                    'ImportUrlCode' => NULL,
                    'AdSite' => NULL,
                    'AdZone' => NULL,
                    'NoPanelAd1' => NULL,
                    'NoPanelAd2' => NULL,
                    'CoreMetricsName' => NULL,
                    'NoIndex' => NULL,
                    'LocalResourceBadges' => 0,
                    'Source' => NULL,
                    'AllowGroups' => 0,
                    'Type' => NULL,
                    'AllowFileUploads' => 0,
                    'ShowDescription' => 0,
                    'Label' => NULL,
                    'UseDownVotes' => NULL,
                    'IdeationType' => NULL,
                    'CountAllDiscussions' => 2,
                    'CountAllComments' => 1,
                    'LastCategoryID' => 0,
                ],
            13 =>
                [
                    'CategoryID' => 13,
                    'ParentCategoryID' => -1,
                    'TreeLeft' => 10,
                    'TreeRight' => 11,
                    'Depth' => 1,
                    'CountCategories' => 0,
                    'CountDiscussions' => 72,
                    'CountComments' => 210,
                    'DateMarkedRead' => NULL,
                    'AllowDiscussions' => 1,
                    'Archived' => 0,
                    'CanDelete' => 1,
                    'Name' => '☢️☢️The Essence☢️☢️',
                    'UrlCode' => 'the-essence',
                    'Description' => '☢️☢️☢️☢️',
                    'Sort' => 10,
                    'CssClass' => 'Cat-Yellow',
                    'Photo' => '',
                    'BannerImage' => '',
                    'PermissionCategoryID' => 13,
                    'PointsCategoryID' => 0,
                    'HideAllDiscussions' => 0,
                    'DisplayAs' => 'Discussions',
                    'InsertUserID' => 0,
                    'UpdateUserID' => 1,
                    'DateInserted' => '2011-10-31 22:18:53',
                    'DateUpdated' => '2020-03-18 21:37:03',
                    'LastCommentID' => 370548,
                    'LastDiscussionID' => 516991,
                    'LastDateInserted' => '2020-02-01 19:56:54',
                    'AllowedDiscussionTypes' => '["Discussion","Poll","Idea"]',
                    'DefaultDiscussionType' => NULL,
                    'ForeignID' => '4',
                    'ImportUrlCode' => NULL,
                    'AdSite' => NULL,
                    'AdZone' => NULL,
                    'NoPanelAd1' => NULL,
                    'NoPanelAd2' => NULL,
                    'CoreMetricsName' => NULL,
                    'NoIndex' => NULL,
                    'LocalResourceBadges' => 0,
                    'Source' => '_source_',
                    'AllowGroups' => 0,
                    'Type' => '',
                    'AllowFileUploads' => 1,
                    'ShowDescription' => 0,
                    'Label' => NULL,
                    'UseDownVotes' => 0,
                    'IdeationType' => NULL,
                    'CountAllDiscussions' => 72,
                    'CountAllComments' => 188,
                    'LastCategoryID' => 13,
                ],
            12 =>
                [
                    'CategoryID' => 12,
                    'ParentCategoryID' => -1,
                    'TreeLeft' => 12,
                    'TreeRight' => 29,
                    'Depth' => 1,
                    'CountCategories' => 5,
                    'CountDiscussions' => 15,
                    'CountComments' => 2,
                    'DateMarkedRead' => NULL,
                    'AllowDiscussions' => 1,
                    'Archived' => 0,
                    'CanDelete' => 1,
                    'Name' => 'Support',
                    'UrlCode' => 'support',
                    'Description' => 'Some general fun discussions.',
                    'Sort' => 12,
                    'CssClass' => 'Cat-Yellow',
                    'Photo' => '',
                    'BannerImage' => '',
                    'PermissionCategoryID' => 12,
                    'PointsCategoryID' => 0,
                    'HideAllDiscussions' => 0,
                    'DisplayAs' => 'Flat',
                    'InsertUserID' => 0,
                    'UpdateUserID' => 1,
                    'DateInserted' => '2011-10-31 22:18:53',
                    'DateUpdated' => '2020-06-06 19:42:19',
                    'LastCommentID' => 370400,
                    'LastDiscussionID' => 516993,
                    'LastDateInserted' => '2017-05-01 21:34:47',
                    'AllowedDiscussionTypes' => '["Discussion","Poll","Idea"]',
                    'DefaultDiscussionType' => NULL,
                    'ForeignID' => '3',
                    'ImportUrlCode' => NULL,
                    'AdSite' => NULL,
                    'AdZone' => NULL,
                    'NoPanelAd1' => NULL,
                    'NoPanelAd2' => NULL,
                    'CoreMetricsName' => NULL,
                    'NoIndex' => NULL,
                    'LocalResourceBadges' => 0,
                    'Source' => '_source_',
                    'AllowGroups' => 0,
                    'Type' => '',
                    'AllowFileUploads' => 0,
                    'ShowDescription' => 0,
                    'Label' => NULL,
                    'UseDownVotes' => NULL,
                    'IdeationType' => NULL,
                    'CountAllDiscussions' => 56,
                    'CountAllComments' => 159,
                    'LastCategoryID' => 14,
                ],
            22 =>
                [
                    'CategoryID' => 22,
                    'ParentCategoryID' => 12,
                    'TreeLeft' => 13,
                    'TreeRight' => 14,
                    'Depth' => 2,
                    'CountCategories' => 0,
                    'CountDiscussions' => 0,
                    'CountComments' => 0,
                    'DateMarkedRead' => NULL,
                    'AllowDiscussions' => 1,
                    'Archived' => 0,
                    'CanDelete' => 1,
                    'Name' => 'News',
                    'UrlCode' => 'news',
                    'Description' => '',
                    'Sort' => 13,
                    'CssClass' => '',
                    'Photo' => NULL,
                    'BannerImage' => NULL,
                    'PermissionCategoryID' => 12,
                    'PointsCategoryID' => 0,
                    'HideAllDiscussions' => 0,
                    'DisplayAs' => 'Default',
                    'InsertUserID' => 1,
                    'UpdateUserID' => 1,
                    'DateInserted' => '2016-05-12 15:16:19',
                    'DateUpdated' => '2016-08-08 18:59:22',
                    'LastCommentID' => NULL,
                    'LastDiscussionID' => NULL,
                    'LastDateInserted' => NULL,
                    'AllowedDiscussionTypes' => 'a:3:{i:0;s:10:"Discussion";i:1;s:4:"Poll";i:2;s:8:"Question";}',
                    'DefaultDiscussionType' => NULL,
                    'ForeignID' => NULL,
                    'ImportUrlCode' => NULL,
                    'AdSite' => NULL,
                    'AdZone' => NULL,
                    'NoPanelAd1' => NULL,
                    'NoPanelAd2' => NULL,
                    'CoreMetricsName' => NULL,
                    'NoIndex' => NULL,
                    'LocalResourceBadges' => 0,
                    'Source' => NULL,
                    'AllowGroups' => 0,
                    'Type' => NULL,
                    'AllowFileUploads' => 0,
                    'ShowDescription' => 0,
                    'Label' => NULL,
                    'UseDownVotes' => 0,
                    'IdeationType' => 'up',
                    'CountAllDiscussions' => 0,
                    'CountAllComments' => -7,
                    'LastCategoryID' => 22,
                ],
            19 =>
                [
                    'CategoryID' => 19,
                    'ParentCategoryID' => 12,
                    'TreeLeft' => 15,
                    'TreeRight' => 16,
                    'Depth' => 2,
                    'CountCategories' => 0,
                    'CountDiscussions' => 5,
                    'CountComments' => 38,
                    'DateMarkedRead' => NULL,
                    'AllowDiscussions' => 1,
                    'Archived' => 0,
                    'CanDelete' => 0,
                    'Name' => 'Reported Posts',
                    'UrlCode' => 'reported-posts',
                    'Description' => NULL,
                    'Sort' => 15,
                    'CssClass' => NULL,
                    'Photo' => NULL,
                    'BannerImage' => NULL,
                    'PermissionCategoryID' => 12,
                    'PointsCategoryID' => 0,
                    'HideAllDiscussions' => 1,
                    'DisplayAs' => 'Discussions',
                    'InsertUserID' => 1,
                    'UpdateUserID' => 1,
                    'DateInserted' => '2013-08-28 21:48:13',
                    'DateUpdated' => '2013-08-28 21:48:13',
                    'LastCommentID' => NULL,
                    'LastDiscussionID' => 516989,
                    'LastDateInserted' => '2015-08-18 16:09:00',
                    'AllowedDiscussionTypes' => NULL,
                    'DefaultDiscussionType' => NULL,
                    'ForeignID' => NULL,
                    'ImportUrlCode' => NULL,
                    'AdSite' => NULL,
                    'AdZone' => NULL,
                    'NoPanelAd1' => NULL,
                    'NoPanelAd2' => NULL,
                    'CoreMetricsName' => NULL,
                    'NoIndex' => NULL,
                    'LocalResourceBadges' => 0,
                    'Source' => NULL,
                    'AllowGroups' => 0,
                    'Type' => 'Reporting',
                    'AllowFileUploads' => 1,
                    'ShowDescription' => 0,
                    'Label' => NULL,
                    'UseDownVotes' => NULL,
                    'IdeationType' => NULL,
                    'CountAllDiscussions' => 5,
                    'CountAllComments' => 38,
                    'LastCategoryID' => 0,
                ],
            7 =>
                [
                    'CategoryID' => 7,
                    'ParentCategoryID' => 12,
                    'TreeLeft' => 17,
                    'TreeRight' => 18,
                    'Depth' => 2,
                    'CountCategories' => 0,
                    'CountDiscussions' => 1,
                    'CountComments' => 0,
                    'DateMarkedRead' => NULL,
                    'AllowDiscussions' => 1,
                    'Archived' => 1,
                    'CanDelete' => 1,
                    'Name' => 'Questions',
                    'UrlCode' => 'questions',
                    'Description' => 'Ask your questions here please!!!',
                    'Sort' => 17,
                    'CssClass' => '',
                    'Photo' => NULL,
                    'BannerImage' => NULL,
                    'PermissionCategoryID' => 12,
                    'PointsCategoryID' => 0,
                    'HideAllDiscussions' => 0,
                    'DisplayAs' => 'Discussions',
                    'InsertUserID' => 1,
                    'UpdateUserID' => 1,
                    'DateInserted' => '2011-10-31 22:18:53',
                    'DateUpdated' => '2016-05-07 15:27:58',
                    'LastCommentID' => 369883,
                    'LastDiscussionID' => 166,
                    'LastDateInserted' => '2012-08-31 15:39:46',
                    'AllowedDiscussionTypes' => 'a:3:{i:0;s:10:"Discussion";i:1;s:4:"Poll";i:2;s:8:"Question";}',
                    'DefaultDiscussionType' => NULL,
                    'ForeignID' => '',
                    'ImportUrlCode' => NULL,
                    'AdSite' => NULL,
                    'AdZone' => NULL,
                    'NoPanelAd1' => NULL,
                    'NoPanelAd2' => NULL,
                    'CoreMetricsName' => NULL,
                    'NoIndex' => NULL,
                    'LocalResourceBadges' => 0,
                    'Source' => '',
                    'AllowGroups' => 0,
                    'Type' => '',
                    'AllowFileUploads' => 0,
                    'ShowDescription' => 0,
                    'Label' => NULL,
                    'UseDownVotes' => NULL,
                    'IdeationType' => NULL,
                    'CountAllDiscussions' => 1,
                    'CountAllComments' => 0,
                    'LastCategoryID' => 0,
                ],
            6 =>
                [
                    'CategoryID' => 6,
                    'ParentCategoryID' => 12,
                    'TreeLeft' => 19,
                    'TreeRight' => 26,
                    'Depth' => 2,
                    'CountCategories' => 3,
                    'CountDiscussions' => 5,
                    'CountComments' => 0,
                    'DateMarkedRead' => NULL,
                    'AllowDiscussions' => 1,
                    'Archived' => 0,
                    'CanDelete' => 1,
                    'Name' => 'Testing',
                    'UrlCode' => 'testing',
                    'Description' => 'Testing with foo column...',
                    'Sort' => 19,
                    'CssClass' => '',
                    'Photo' => NULL,
                    'BannerImage' => NULL,
                    'PermissionCategoryID' => 6,
                    'PointsCategoryID' => 0,
                    'HideAllDiscussions' => 0,
                    'DisplayAs' => 'Heading',
                    'InsertUserID' => 1,
                    'UpdateUserID' => 1,
                    'DateInserted' => '2011-08-25 17:11:06',
                    'DateUpdated' => '2016-05-16 23:20:02',
                    'LastCommentID' => NULL,
                    'LastDiscussionID' => 517000,
                    'LastDateInserted' => '2016-05-11 19:15:26',
                    'AllowedDiscussionTypes' => 'a:3:{i:0;s:10:"Discussion";i:1;s:4:"Poll";i:2;s:8:"Question";}',
                    'DefaultDiscussionType' => NULL,
                    'ForeignID' => '',
                    'ImportUrlCode' => NULL,
                    'AdSite' => NULL,
                    'AdZone' => NULL,
                    'NoPanelAd1' => NULL,
                    'NoPanelAd2' => NULL,
                    'CoreMetricsName' => NULL,
                    'NoIndex' => NULL,
                    'LocalResourceBadges' => 0,
                    'Source' => '',
                    'AllowGroups' => 0,
                    'Type' => '',
                    'AllowFileUploads' => 1,
                    'ShowDescription' => 0,
                    'Label' => NULL,
                    'UseDownVotes' => NULL,
                    'IdeationType' => NULL,
                    'CountAllDiscussions' => 17,
                    'CountAllComments' => 44,
                    'LastCategoryID' => 0,
                ],
            4 =>
                [
                    'CategoryID' => 4,
                    'ParentCategoryID' => 6,
                    'TreeLeft' => 20,
                    'TreeRight' => 21,
                    'Depth' => 3,
                    'CountCategories' => 1,
                    'CountDiscussions' => 3,
                    'CountComments' => 0,
                    'DateMarkedRead' => NULL,
                    'AllowDiscussions' => 1,
                    'Archived' => 0,
                    'CanDelete' => 1,
                    'Name' => 'Todd@Burry',
                    'UrlCode' => 'todd@burry',
                    'Description' => '',
                    'Sort' => 20,
                    'CssClass' => NULL,
                    'Photo' => NULL,
                    'BannerImage' => NULL,
                    'PermissionCategoryID' => 6,
                    'PointsCategoryID' => 0,
                    'HideAllDiscussions' => 0,
                    'DisplayAs' => 'Categories',
                    'InsertUserID' => 1,
                    'UpdateUserID' => 1,
                    'DateInserted' => '2011-06-03 15:58:24',
                    'DateUpdated' => '2011-08-25 17:10:34',
                    'LastCommentID' => NULL,
                    'LastDiscussionID' => 88765,
                    'LastDateInserted' => '2013-07-19 20:48:46',
                    'AllowedDiscussionTypes' => NULL,
                    'DefaultDiscussionType' => NULL,
                    'ForeignID' => '',
                    'ImportUrlCode' => NULL,
                    'AdSite' => NULL,
                    'AdZone' => NULL,
                    'NoPanelAd1' => NULL,
                    'NoPanelAd2' => NULL,
                    'CoreMetricsName' => NULL,
                    'NoIndex' => NULL,
                    'LocalResourceBadges' => 0,
                    'Source' => '',
                    'AllowGroups' => 0,
                    'Type' => '',
                    'AllowFileUploads' => 1,
                    'ShowDescription' => 0,
                    'Label' => NULL,
                    'UseDownVotes' => NULL,
                    'IdeationType' => NULL,
                    'CountAllDiscussions' => 3,
                    'CountAllComments' => 0,
                    'LastCategoryID' => 0,
                ],
            2 =>
                [
                    'CategoryID' => 2,
                    'ParentCategoryID' => 6,
                    'TreeLeft' => 22,
                    'TreeRight' => 23,
                    'Depth' => 3,
                    'CountCategories' => 0,
                    'CountDiscussions' => 9,
                    'CountComments' => 44,
                    'DateMarkedRead' => NULL,
                    'AllowDiscussions' => 1,
                    'Archived' => 0,
                    'CanDelete' => 1,
                    'Name' => 'Email',
                    'UrlCode' => 'inbox',
                    'Description' => '',
                    'Sort' => 22,
                    'CssClass' => '',
                    'Photo' => NULL,
                    'BannerImage' => NULL,
                    'PermissionCategoryID' => 6,
                    'PointsCategoryID' => 0,
                    'HideAllDiscussions' => 0,
                    'DisplayAs' => 'Discussions',
                    'InsertUserID' => 1,
                    'UpdateUserID' => 1,
                    'DateInserted' => '2011-05-04 13:18:38',
                    'DateUpdated' => '2013-08-30 17:42:20',
                    'LastCommentID' => 370084,
                    'LastDiscussionID' => 88782,
                    'LastDateInserted' => '2014-06-11 23:52:50',
                    'AllowedDiscussionTypes' => 'a:3:{i:0;s:10:"Discussion";i:1;s:4:"Poll";i:2;s:8:"Question";}',
                    'DefaultDiscussionType' => NULL,
                    'ForeignID' => '',
                    'ImportUrlCode' => NULL,
                    'AdSite' => NULL,
                    'AdZone' => NULL,
                    'NoPanelAd1' => NULL,
                    'NoPanelAd2' => NULL,
                    'CoreMetricsName' => NULL,
                    'NoIndex' => NULL,
                    'LocalResourceBadges' => 0,
                    'Source' => '',
                    'AllowGroups' => 0,
                    'Type' => '',
                    'AllowFileUploads' => 1,
                    'ShowDescription' => 0,
                    'Label' => NULL,
                    'UseDownVotes' => NULL,
                    'IdeationType' => NULL,
                    'CountAllDiscussions' => 9,
                    'CountAllComments' => 44,
                    'LastCategoryID' => 0,
                ],
            20 =>
                [
                    'CategoryID' => 20,
                    'ParentCategoryID' => 6,
                    'TreeLeft' => 24,
                    'TreeRight' => 25,
                    'Depth' => 3,
                    'CountCategories' => 0,
                    'CountDiscussions' => 0,
                    'CountComments' => 0,
                    'DateMarkedRead' => NULL,
                    'AllowDiscussions' => 1,
                    'Archived' => 0,
                    'CanDelete' => 1,
                    'Name' => 'noop',
                    'UrlCode' => 'noop',
                    'Description' => '',
                    'Sort' => 24,
                    'CssClass' => '',
                    'Photo' => NULL,
                    'BannerImage' => NULL,
                    'PermissionCategoryID' => 6,
                    'PointsCategoryID' => 0,
                    'HideAllDiscussions' => 0,
                    'DisplayAs' => 'Default',
                    'InsertUserID' => 1,
                    'UpdateUserID' => 1,
                    'DateInserted' => '2014-03-21 20:28:38',
                    'DateUpdated' => '2014-03-21 20:28:38',
                    'LastCommentID' => NULL,
                    'LastDiscussionID' => NULL,
                    'LastDateInserted' => NULL,
                    'AllowedDiscussionTypes' => NULL,
                    'DefaultDiscussionType' => NULL,
                    'ForeignID' => NULL,
                    'ImportUrlCode' => NULL,
                    'AdSite' => NULL,
                    'AdZone' => NULL,
                    'NoPanelAd1' => NULL,
                    'NoPanelAd2' => NULL,
                    'CoreMetricsName' => NULL,
                    'NoIndex' => NULL,
                    'LocalResourceBadges' => 0,
                    'Source' => NULL,
                    'AllowGroups' => 0,
                    'Type' => NULL,
                    'AllowFileUploads' => 1,
                    'ShowDescription' => 0,
                    'Label' => NULL,
                    'UseDownVotes' => NULL,
                    'IdeationType' => NULL,
                    'CountAllDiscussions' => 0,
                    'CountAllComments' => 0,
                    'LastCategoryID' => 0,
                ],
            14 =>
                [
                    'CategoryID' => 14,
                    'ParentCategoryID' => 12,
                    'TreeLeft' => 27,
                    'TreeRight' => 28,
                    'Depth' => 2,
                    'CountCategories' => 0,
                    'CountDiscussions' => 19,
                    'CountComments' => 100,
                    'DateMarkedRead' => NULL,
                    'AllowDiscussions' => 1,
                    'Archived' => 0,
                    'CanDelete' => 1,
                    'Name' => 'Ideas',
                    'UrlCode' => 'ideas',
                    'Description' => '',
                    'Sort' => 27,
                    'CssClass' => '',
                    'Photo' => NULL,
                    'BannerImage' => NULL,
                    'PermissionCategoryID' => 12,
                    'PointsCategoryID' => 0,
                    'HideAllDiscussions' => 0,
                    'DisplayAs' => 'Default',
                    'InsertUserID' => 74195,
                    'UpdateUserID' => 1,
                    'DateInserted' => '2012-07-16 19:37:39',
                    'DateUpdated' => '2016-05-07 15:31:16',
                    'LastCommentID' => 370400,
                    'LastDiscussionID' => 516993,
                    'LastDateInserted' => '2017-05-01 21:34:47',
                    'AllowedDiscussionTypes' => 'a:4:{i:0;s:10:"Discussion";i:1;s:4:"Poll";i:2;s:8:"Question";i:3;s:4:"Idea";}',
                    'DefaultDiscussionType' => NULL,
                    'ForeignID' => NULL,
                    'ImportUrlCode' => NULL,
                    'AdSite' => NULL,
                    'AdZone' => NULL,
                    'NoPanelAd1' => NULL,
                    'NoPanelAd2' => NULL,
                    'CoreMetricsName' => NULL,
                    'NoIndex' => NULL,
                    'LocalResourceBadges' => 0,
                    'Source' => NULL,
                    'AllowGroups' => 0,
                    'Type' => '',
                    'AllowFileUploads' => 0,
                    'ShowDescription' => 0,
                    'Label' => NULL,
                    'UseDownVotes' => NULL,
                    'IdeationType' => 'up',
                    'CountAllDiscussions' => 18,
                    'CountAllComments' => 82,
                    'LastCategoryID' => 14,
                ],
            15 =>
                [
                    'CategoryID' => 15,
                    'ParentCategoryID' => -1,
                    'TreeLeft' => 30,
                    'TreeRight' => 41,
                    'Depth' => 1,
                    'CountCategories' => 1,
                    'CountDiscussions' => 3,
                    'CountComments' => 9,
                    'DateMarkedRead' => NULL,
                    'AllowDiscussions' => 1,
                    'Archived' => 0,
                    'CanDelete' => 1,
                    'Name' => 'Other',
                    'UrlCode' => 'other',
                    'Description' => '',
                    'Sort' => 30,
                    'CssClass' => '',
                    'Photo' => NULL,
                    'BannerImage' => NULL,
                    'PermissionCategoryID' => -1,
                    'PointsCategoryID' => 0,
                    'HideAllDiscussions' => 0,
                    'DisplayAs' => 'Heading',
                    'InsertUserID' => 1,
                    'UpdateUserID' => 1,
                    'DateInserted' => '2012-07-16 20:15:08',
                    'DateUpdated' => '2016-05-12 14:09:19',
                    'LastCommentID' => 370472,
                    'LastDiscussionID' => 517028,
                    'LastDateInserted' => '2019-10-22 19:50:14',
                    'AllowedDiscussionTypes' => 'a:4:{i:0;s:10:"Discussion";i:1;s:4:"Poll";i:2;s:8:"Question";i:3;s:4:"Idea";}',
                    'DefaultDiscussionType' => NULL,
                    'ForeignID' => NULL,
                    'ImportUrlCode' => NULL,
                    'AdSite' => NULL,
                    'AdZone' => NULL,
                    'NoPanelAd1' => NULL,
                    'NoPanelAd2' => NULL,
                    'CoreMetricsName' => NULL,
                    'NoIndex' => NULL,
                    'LocalResourceBadges' => 0,
                    'Source' => NULL,
                    'AllowGroups' => 0,
                    'Type' => '',
                    'AllowFileUploads' => 0,
                    'ShowDescription' => 0,
                    'Label' => NULL,
                    'UseDownVotes' => NULL,
                    'IdeationType' => NULL,
                    'CountAllDiscussions' => 118,
                    'CountAllComments' => 285,
                    'LastCategoryID' => 13,
                ],
            11 =>
                [
                    'CategoryID' => 11,
                    'ParentCategoryID' => 15,
                    'TreeLeft' => 31,
                    'TreeRight' => 40,
                    'Depth' => 2,
                    'CountCategories' => 2,
                    'CountDiscussions' => 5,
                    'CountComments' => 0,
                    'DateMarkedRead' => NULL,
                    'AllowDiscussions' => 1,
                    'Archived' => 0,
                    'CanDelete' => 1,
                    'Name' => 'Uncategorized',
                    'UrlCode' => 'uncategorized',
                    'Description' => NULL,
                    'Sort' => 31,
                    'CssClass' => NULL,
                    'Photo' => NULL,
                    'BannerImage' => NULL,
                    'PermissionCategoryID' => -1,
                    'PointsCategoryID' => 0,
                    'HideAllDiscussions' => 0,
                    'DisplayAs' => 'Default',
                    'InsertUserID' => 0,
                    'UpdateUserID' => NULL,
                    'DateInserted' => '2011-10-31 22:18:53',
                    'DateUpdated' => '2011-10-31 22:18:53',
                    'LastCommentID' => 370472,
                    'LastDiscussionID' => 517028,
                    'LastDateInserted' => '2019-10-22 19:50:14',
                    'AllowedDiscussionTypes' => NULL,
                    'DefaultDiscussionType' => NULL,
                    'ForeignID' => '1',
                    'ImportUrlCode' => NULL,
                    'AdSite' => NULL,
                    'AdZone' => NULL,
                    'NoPanelAd1' => NULL,
                    'NoPanelAd2' => NULL,
                    'CoreMetricsName' => NULL,
                    'NoIndex' => NULL,
                    'LocalResourceBadges' => 0,
                    'Source' => '_source_',
                    'AllowGroups' => 0,
                    'Type' => '',
                    'AllowFileUploads' => 1,
                    'ShowDescription' => 0,
                    'Label' => NULL,
                    'UseDownVotes' => NULL,
                    'IdeationType' => NULL,
                    'CountAllDiscussions' => 115,
                    'CountAllComments' => 276,
                    'LastCategoryID' => 13,
                ],
            17 =>
                [
                    'CategoryID' => 17,
                    'ParentCategoryID' => 11,
                    'TreeLeft' => 32,
                    'TreeRight' => 33,
                    'Depth' => 3,
                    'CountCategories' => 1,
                    'CountDiscussions' => 16,
                    'CountComments' => 31,
                    'DateMarkedRead' => NULL,
                    'AllowDiscussions' => 1,
                    'Archived' => 0,
                    'CanDelete' => 1,
                    'Name' => 'Social Groups',
                    'UrlCode' => 'social-groups',
                    'Description' => '',
                    'Sort' => 32,
                    'CssClass' => '',
                    'Photo' => NULL,
                    'BannerImage' => NULL,
                    'PermissionCategoryID' => 17,
                    'PointsCategoryID' => 0,
                    'HideAllDiscussions' => 1,
                    'DisplayAs' => 'Discussions',
                    'InsertUserID' => 1,
                    'UpdateUserID' => 1,
                    'DateInserted' => '2013-06-04 16:35:37',
                    'DateUpdated' => '2014-12-17 16:55:20',
                    'LastCommentID' => NULL,
                    'LastDiscussionID' => 88842,
                    'LastDateInserted' => '2014-11-08 00:01:08',
                    'AllowedDiscussionTypes' => 'a:2:{i:0;s:10:"Discussion";i:1;s:8:"Question";}',
                    'DefaultDiscussionType' => NULL,
                    'ForeignID' => NULL,
                    'ImportUrlCode' => NULL,
                    'AdSite' => NULL,
                    'AdZone' => NULL,
                    'NoPanelAd1' => NULL,
                    'NoPanelAd2' => NULL,
                    'CoreMetricsName' => NULL,
                    'NoIndex' => NULL,
                    'LocalResourceBadges' => 0,
                    'Source' => NULL,
                    'AllowGroups' => 1,
                    'Type' => '',
                    'AllowFileUploads' => 1,
                    'ShowDescription' => 0,
                    'Label' => NULL,
                    'UseDownVotes' => NULL,
                    'IdeationType' => NULL,
                    'CountAllDiscussions' => 16,
                    'CountAllComments' => 31,
                    'LastCategoryID' => 0,
                ],
            1 =>
                [
                    'CategoryID' => 1,
                    'ParentCategoryID' => 11,
                    'TreeLeft' => 34,
                    'TreeRight' => 39,
                    'Depth' => 3,
                    'CountCategories' => 2,
                    'CountDiscussions' => 13,
                    'CountComments' => 50,
                    'DateMarkedRead' => NULL,
                    'AllowDiscussions' => 1,
                    'Archived' => 0,
                    'CanDelete' => 1,
                    'Name' => 'Archive',
                    'UrlCode' => 'archive',
                    'Description' => 'General discussions',
                    'Sort' => 34,
                    'CssClass' => '',
                    'Photo' => NULL,
                    'BannerImage' => NULL,
                    'PermissionCategoryID' => -1,
                    'PointsCategoryID' => 0,
                    'HideAllDiscussions' => 0,
                    'DisplayAs' => 'Heading',
                    'InsertUserID' => 1,
                    'UpdateUserID' => 1,
                    'DateInserted' => '2011-04-20 11:21:38',
                    'DateUpdated' => '2016-05-07 15:30:22',
                    'LastCommentID' => 370472,
                    'LastDiscussionID' => 517028,
                    'LastDateInserted' => '2019-10-22 19:50:14',
                    'AllowedDiscussionTypes' => 'a:3:{i:0;s:10:"Discussion";i:1;s:4:"Poll";i:2;s:8:"Question";}',
                    'DefaultDiscussionType' => NULL,
                    'ForeignID' => '',
                    'ImportUrlCode' => NULL,
                    'AdSite' => NULL,
                    'AdZone' => NULL,
                    'NoPanelAd1' => NULL,
                    'NoPanelAd2' => NULL,
                    'CoreMetricsName' => NULL,
                    'NoIndex' => NULL,
                    'LocalResourceBadges' => 0,
                    'Source' => '',
                    'AllowGroups' => 0,
                    'Type' => '',
                    'AllowFileUploads' => 0,
                    'ShowDescription' => 0,
                    'Label' => NULL,
                    'UseDownVotes' => NULL,
                    'IdeationType' => NULL,
                    'CountAllDiscussions' => 95,
                    'CountAllComments' => 245,
                    'LastCategoryID' => 13,
                ],
            3 =>
                [
                    'CategoryID' => 3,
                    'ParentCategoryID' => 1,
                    'TreeLeft' => 35,
                    'TreeRight' => 36,
                    'Depth' => 4,
                    'CountCategories' => 0,
                    'CountDiscussions' => 8,
                    'CountComments' => 20,
                    'DateMarkedRead' => NULL,
                    'AllowDiscussions' => 1,
                    'Archived' => 0,
                    'CanDelete' => 1,
                    'Name' => 'One, two, three...',
                    'UrlCode' => 'one-two-three',
                    'Description' => '...',
                    'Sort' => 35,
                    'CssClass' => '',
                    'Photo' => NULL,
                    'BannerImage' => NULL,
                    'PermissionCategoryID' => 3,
                    'PointsCategoryID' => 0,
                    'HideAllDiscussions' => 0,
                    'DisplayAs' => 'Default',
                    'InsertUserID' => 1,
                    'UpdateUserID' => 1,
                    'DateInserted' => '2011-05-04 13:25:57',
                    'DateUpdated' => '2013-10-04 15:11:15',
                    'LastCommentID' => 370413,
                    'LastDiscussionID' => 516987,
                    'LastDateInserted' => '2017-08-01 17:15:14',
                    'AllowedDiscussionTypes' => 'a:2:{i:0;s:10:"Discussion";i:1;s:8:"Question";}',
                    'DefaultDiscussionType' => NULL,
                    'ForeignID' => '',
                    'ImportUrlCode' => NULL,
                    'AdSite' => NULL,
                    'AdZone' => NULL,
                    'NoPanelAd1' => NULL,
                    'NoPanelAd2' => NULL,
                    'CoreMetricsName' => NULL,
                    'NoIndex' => NULL,
                    'LocalResourceBadges' => 0,
                    'Source' => '',
                    'AllowGroups' => 0,
                    'Type' => '',
                    'AllowFileUploads' => 1,
                    'ShowDescription' => 0,
                    'Label' => NULL,
                    'UseDownVotes' => NULL,
                    'IdeationType' => NULL,
                    'CountAllDiscussions' => 8,
                    'CountAllComments' => 4,
                    'LastCategoryID' => 3,
                ],
            16 =>
                [
                    'CategoryID' => 16,
                    'ParentCategoryID' => 1,
                    'TreeLeft' => 37,
                    'TreeRight' => 38,
                    'Depth' => 4,
                    'CountCategories' => 2,
                    'CountDiscussions' => 2,
                    'CountComments' => 0,
                    'DateMarkedRead' => NULL,
                    'AllowDiscussions' => 0,
                    'Archived' => 0,
                    'CanDelete' => 1,
                    'Name' => 'General',
                    'UrlCode' => 'testcat02',
                    'Description' => 'Mon Jul 16 21:19:08 2012',
                    'Sort' => 37,
                    'CssClass' => '',
                    'Photo' => NULL,
                    'BannerImage' => NULL,
                    'PermissionCategoryID' => -1,
                    'PointsCategoryID' => 0,
                    'HideAllDiscussions' => 0,
                    'DisplayAs' => 'Default',
                    'InsertUserID' => 74195,
                    'UpdateUserID' => 1,
                    'DateInserted' => '2012-07-16 20:16:06',
                    'DateUpdated' => '2016-05-17 00:56:22',
                    'LastCommentID' => NULL,
                    'LastDiscussionID' => 88763,
                    'LastDateInserted' => '2013-07-19 20:48:45',
                    'AllowedDiscussionTypes' => 'a:3:{i:0;s:10:"Discussion";i:1;s:4:"Poll";i:2;s:8:"Question";}',
                    'DefaultDiscussionType' => NULL,
                    'ForeignID' => NULL,
                    'ImportUrlCode' => NULL,
                    'AdSite' => NULL,
                    'AdZone' => NULL,
                    'NoPanelAd1' => NULL,
                    'NoPanelAd2' => NULL,
                    'CoreMetricsName' => NULL,
                    'NoIndex' => NULL,
                    'LocalResourceBadges' => 0,
                    'Source' => NULL,
                    'AllowGroups' => 0,
                    'Type' => '',
                    'AllowFileUploads' => 1,
                    'ShowDescription' => 0,
                    'Label' => NULL,
                    'UseDownVotes' => NULL,
                    'IdeationType' => NULL,
                    'CountAllDiscussions' => 2,
                    'CountAllComments' => 0,
                    'LastCategoryID' => 0,
                ],
        ];
        $r = self::pruneColumns($r);
        return $r;
    }

    public function getCategoryFlattenData(): array {
        return [
            -1 =>
                [
                    'CategoryID' => -1,
                    'TreeLeft' => 1,
                    'TreeRight' => 66,
                    'ParentCategoryID' => NULL,
                    'Name' => 'Root',
                    'DisplayAs' => 'Categories',
                ],
            5 =>
                [
                    'CategoryID' => 5,
                    'TreeLeft' => 2,
                    'TreeRight' => 5,
                    'ParentCategoryID' => -1,
                    'Name' => 'Test Parent Category',
                    'DisplayAs' => 'Discussions',
                ],
            6 =>
                [
                    'CategoryID' => 6,
                    'TreeLeft' => 3,
                    'TreeRight' => 4,
                    'ParentCategoryID' => 5,
                    'Name' => 'Test Child Category',
                    'DisplayAs' => 'Discussions',
                ],
            1 =>
                [
                    'CategoryID' => 1,
                    'TreeLeft' => 6,
                    'TreeRight' => 65,
                    'ParentCategoryID' => -1,
                    'Name' => 'General',
                    'DisplayAs' => 'Discussions',
                ],
            33 =>
                [
                    'CategoryID' => 33,
                    'TreeLeft' => 7,
                    'TreeRight' => 8,
                    'ParentCategoryID' => 1,
                    'Name' => 'Test Category 28',
                    'DisplayAs' => 'Flat',
                ],
            32 =>
                [
                    'CategoryID' => 32,
                    'TreeLeft' => 9,
                    'TreeRight' => 10,
                    'ParentCategoryID' => 1,
                    'Name' => 'Test Category 27',
                    'DisplayAs' => 'Flat',
                ],
            31 =>
                [
                    'CategoryID' => 31,
                    'TreeLeft' => 11,
                    'TreeRight' => 12,
                    'ParentCategoryID' => 1,
                    'Name' => 'Test Category 26',
                    'DisplayAs' => 'Flat',
                ],
            30 =>
                [
                    'CategoryID' => 30,
                    'TreeLeft' => 13,
                    'TreeRight' => 14,
                    'ParentCategoryID' => 1,
                    'Name' => 'Test Category 25',
                    'DisplayAs' => 'Flat',
                ],
            29 =>
                [
                    'CategoryID' => 29,
                    'TreeLeft' => 15,
                    'TreeRight' => 16,
                    'ParentCategoryID' => 1,
                    'Name' => 'Test Category 24',
                    'DisplayAs' => 'Flat',
                ],
            28 =>
                [
                    'CategoryID' => 28,
                    'TreeLeft' => 17,
                    'TreeRight' => 18,
                    'ParentCategoryID' => 1,
                    'Name' => 'Test Category 23',
                    'DisplayAs' => 'Flat',
                ],
            27 =>
                [
                    'CategoryID' => 27,
                    'TreeLeft' => 19,
                    'TreeRight' => 20,
                    'ParentCategoryID' => 1,
                    'Name' => 'Test Category 22',
                    'DisplayAs' => 'Flat',
                ],
            26 =>
                [
                    'CategoryID' => 26,
                    'TreeLeft' => 21,
                    'TreeRight' => 22,
                    'ParentCategoryID' => 1,
                    'Name' => 'Test Category 21',
                    'DisplayAs' => 'Flat',
                ],
            24 =>
                [
                    'CategoryID' => 24,
                    'TreeLeft' => 23,
                    'TreeRight' => 24,
                    'ParentCategoryID' => 1,
                    'Name' => 'Test Category 19',
                    'DisplayAs' => 'Categories',
                ],
            23 =>
                [
                    'CategoryID' => 23,
                    'TreeLeft' => 25,
                    'TreeRight' => 26,
                    'ParentCategoryID' => 1,
                    'Name' => 'Test Category 18',
                    'DisplayAs' => 'Flat',
                ],
            21 =>
                [
                    'CategoryID' => 21,
                    'TreeLeft' => 27,
                    'TreeRight' => 28,
                    'ParentCategoryID' => 1,
                    'Name' => 'Test Category 16 Tue, 09 Jun 2020 21:45:14 +0000',
                    'DisplayAs' => 'Flat',
                ],
            20 =>
                [
                    'CategoryID' => 20,
                    'TreeLeft' => 29,
                    'TreeRight' => 30,
                    'ParentCategoryID' => 1,
                    'Name' => 'Test Category 15',
                    'DisplayAs' => 'Flat',
                ],
            19 =>
                [
                    'CategoryID' => 19,
                    'TreeLeft' => 31,
                    'TreeRight' => 32,
                    'ParentCategoryID' => 1,
                    'Name' => 'Test Category 14',
                    'DisplayAs' => 'Flat',
                ],
            18 =>
                [
                    'CategoryID' => 18,
                    'TreeLeft' => 33,
                    'TreeRight' => 34,
                    'ParentCategoryID' => 1,
                    'Name' => 'Test Category 12',
                    'DisplayAs' => 'Flat',
                ],
            17 =>
                [
                    'CategoryID' => 17,
                    'TreeLeft' => 35,
                    'TreeRight' => 36,
                    'ParentCategoryID' => 1,
                    'Name' => 'Test Category 11',
                    'DisplayAs' => 'Flat',
                ],
            15 =>
                [
                    'CategoryID' => 15,
                    'TreeLeft' => 37,
                    'TreeRight' => 38,
                    'ParentCategoryID' => 1,
                    'Name' => 'Test Category 8',
                    'DisplayAs' => 'Flat',
                ],
            14 =>
                [
                    'CategoryID' => 14,
                    'TreeLeft' => 39,
                    'TreeRight' => 40,
                    'ParentCategoryID' => 1,
                    'Name' => 'Test Category 7',
                    'DisplayAs' => 'Flat',
                ],
            13 =>
                [
                    'CategoryID' => 13,
                    'TreeLeft' => 41,
                    'TreeRight' => 42,
                    'ParentCategoryID' => 1,
                    'Name' => 'Test Category 6',
                    'DisplayAs' => 'Categories',
                ],
            12 =>
                [
                    'CategoryID' => 12,
                    'TreeLeft' => 43,
                    'TreeRight' => 44,
                    'ParentCategoryID' => 1,
                    'Name' => 'Test Category 5',
                    'DisplayAs' => 'Flat',
                ],
            11 =>
                [
                    'CategoryID' => 11,
                    'TreeLeft' => 45,
                    'TreeRight' => 46,
                    'ParentCategoryID' => 1,
                    'Name' => 'Test Category 4',
                    'DisplayAs' => 'Flat',
                ],
            9 =>
                [
                    'CategoryID' => 9,
                    'TreeLeft' => 47,
                    'TreeRight' => 50,
                    'ParentCategoryID' => 1,
                    'Name' => 'Test Parent as Child',
                    'DisplayAs' => 'Discussions',
                ],
            10 =>
                [
                    'CategoryID' => 10,
                    'TreeLeft' => 48,
                    'TreeRight' => 49,
                    'ParentCategoryID' => 9,
                    'Name' => 'Test Child as Parent',
                    'DisplayAs' => 'Discussions',
                ],
            8 =>
                [
                    'CategoryID' => 8,
                    'TreeLeft' => 51,
                    'TreeRight' => 52,
                    'ParentCategoryID' => 1,
                    'Name' => 'Test Child Parent',
                    'DisplayAs' => 'Discussions',
                ],
            7 =>
                [
                    'CategoryID' => 7,
                    'TreeLeft' => 53,
                    'TreeRight' => 54,
                    'ParentCategoryID' => 1,
                    'Name' => 'Test Bad Parent',
                    'DisplayAs' => 'Discussions',
                ],
            4 =>
                [
                    'CategoryID' => 4,
                    'TreeLeft' => 55,
                    'TreeRight' => 56,
                    'ParentCategoryID' => 1,
                    'Name' => 'Test Category 3',
                    'DisplayAs' => 'Discussions',
                ],
            3 =>
                [
                    'CategoryID' => 3,
                    'TreeLeft' => 57,
                    'TreeRight' => 58,
                    'ParentCategoryID' => 1,
                    'Name' => 'Test Category 2',
                    'DisplayAs' => 'Flat',
                ],
            2 =>
                [
                    'CategoryID' => 2,
                    'TreeLeft' => 59,
                    'TreeRight' => 64,
                    'ParentCategoryID' => 1,
                    'Name' => 'Test Category 1',
                    'DisplayAs' => 'Flat',
                ],
            22 =>
                [
                    'CategoryID' => 22,
                    'TreeLeft' => 60,
                    'TreeRight' => 61,
                    'ParentCategoryID' => 2,
                    'Name' => 'Test Category 17',
                    'DisplayAs' => 'Flat',
                ],
            16 =>
                [
                    'CategoryID' => 16,
                    'TreeLeft' => 62,
                    'TreeRight' => 63,
                    'ParentCategoryID' => 2,
                    'Name' => 'Test Category 10 Tue, 09 Jun 2020 21:45:13 +0000',
                    'DisplayAs' => 'Categories',
                ],
        ];
    }

    private function assertSortedCategories(array $categories, array $sorted): void {
        $this->assertSame(count($categories), count($sorted), 'The sorted categories has a different count from the original.');

        $categories = array_column($categories, null, 'CategoryID');
        $sorted = array_column($sorted, null, 'CategoryID');

        // Look for items in categories that are not in sorted.
        $notInSorted = array_diff_key($categories, $sorted);
        if (!empty($notInSorted)) {
            $this->fail("The following categories are missing from sorted: ".implode(', ', array_column($notInSorted, 'Name')));
        }

        $notInSorted = array_diff_key($sorted, $categories);
        if (!empty($notInSorted)) {
            $this->fail("The following categories are missing from original: ".implode(', ', array_column($notInSorted, 'Name')));
        }
    }
}
