openapi: 3.0.2
info:
paths:
    /post-fields:
        x-hidden: true
        get:
            summary: List post fields.
            parameters:
                - name: apiName
                  description: Filter by apiName.
                  in: query
                  schema:
                      type: string
                - name: postTypeID
                  description: Filter by post type.
                  in: query
                  schema:
                      type: string
                - name: label
                  description: Filter by label.
                  in: query
                  schema:
                      type: string
                - name: dataType
                  description: Filter by data type.
                  in: query
                  schema:
                      type: string
                - name: formType
                  description: Filter by form type.
                  in: query
                  schema:
                      type: string
                - name: visibility
                  description: Filter by visibility.
                  in: query
                  schema:
                      type: string
                - name: isRequired
                  description: Filter by required post fields.
                  in: query
                  schema:
                      type: boolean
                - name: isActive
                  description: Filter by active post fields.
                  in: query
                  schema:
                      type: boolean
                - $ref: "../../dashboard/openapi/parameters.yml#/components/parameters/Page"
            responses:
                "200":
                    content:
                        "application/json":
                            schema:
                                items:
                                    $ref: "#/components/schemas/PostField"
                                type: array
                    description: Success
                "400":
                    description: Bad Request
                "403":
                    description: Forbidden
                "500":
                    description: Server Error
            tags:
                - Post Types & Post Fields
        post:
            summary: Create a post field.
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/PostFieldPost"
            tags:
                - Post Types & Post Fields
            responses:
                "201":
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/PostField"
                    description: Success
                "400":
                    description: Bad Request
                "403":
                    description: Forbidden
                "500":
                    description: Server Error

    /post-fields/{postFieldID}:
        x-hidden: true
        get:
            summary: Get a post field.
            tags:
                - Post Types & Post Fields
            parameters:
                - description: The ID of the post field.
                  in: path
                  name: postFieldID
                  required: true
                  schema:
                      type: integer
            responses:
                "200":
                    description: Success
                    content:
                        "application/json":
                            schema:
                                $ref: "#/components/schemas/PostField"
                "404":
                    description: Not Found
        patch:
            summary: Update a post field.
            tags:
                - Post Types & Post Fields
            parameters:
                - description: The ID of the post field.
                  in: path
                  name: postFieldID
                  required: true
                  schema:
                      type: integer
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/PostFieldPatch"
                required: true
            responses:
                "200":
                    content:
                        "application/json":
                            schema:
                                $ref: "#/components/schemas/PostField"
                    description: Success
                "400":
                    description: Bad Request
                "403":
                    description: Forbidden
                "404":
                    description: Not Found
                "500":
                    description: Server Error
        delete:
            summary: Delete a post field.
            parameters:
                - description: The ID of the post field
                  in: path
                  name: postFieldID
                  required: true
                  schema:
                      type: integer
            responses:
                "204":
                    description: Success
                "400":
                    description: Bad Request
                "403":
                    description: Forbidden
                "404":
                    description: Not Found
                "500":
                    description: Server Error
            tags:
                - Post Types & Post Fields
    /post-fields/sorts:
        put:
            tags:
                - Post Types & Post Fields
            summary: Update the sort values of post fields.
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            additionalProperties:
                                type: integer

            responses:
                "200":
                    description: Success
                "400":
                    description: Bad Request
                "403":
                    description: Forbidden
                "500":
                    description: Server Error
components:
    schemas:
        PostFieldPost:
            properties:
                apiName:
                    description: The apiName of the post field.
                    type: string
                postTypeID:
                    description: The ID of an associated post type.
                    type: string
                label:
                    description: The label of the post field.
                    type: string
                description:
                    description: The description of the post field.
                    type: string
                dataType:
                    description: The data type of the post field.
                    type: string
                formType:
                    description: The form type of the post field.
                    type: string
                visibility:
                    description: The visibility of the post field.
                    type: string
                isRequired:
                    description: Whether the post field is required.
                    type: string
                isActive:
                    description: Whether the post field is active.
                    type: string
            required:
                - apiName
                - postTypeID
                - label
                - description
                - dataType
                - formType
                - visibility
                - isRequired
                - isActive
            type: object
        PostFieldPatch:
            properties:
                label:
                    description: The label of the post field.
                    type: string
                description:
                    description: The description of the post field.
                    type: string
                formType:
                    description: The form type of the post field.
                    type: string
                visibility:
                    description: The visibility of the post field.
                    type: string
                isRequired:
                    description: Whether the post field is required.
                    type: string
                isActive:
                    description: Whether the post field is active.
                    type: string
            required:
                - label
                - description
                - formType
                - visibility
                - isRequired
                - isActive
            type: object
        PostField:
            properties:
                postFieldID:
                    description: The ID of the post field.
                    type: string
                apiName:
                    description: The apiName of the post field.
                    type: string
                postTypeID:
                    description: The ID of an associated post type.
                    type: string
                label:
                    description: The label of the post field.
                    type: string
                description:
                    description: The description of the post field.
                    type: string
                dataType:
                    description: The data type of the post field.
                    type: string
                formType:
                    description: The form type of the post field.
                    type: string
                visibility:
                    description: The visibility of the post field.
                    type: string
                displayOptions:
                    description: The display options of the post field.
                    type: string
                dropdownOptions:
                    description: The dropdown options of the post field.
                    type: string
                isRequired:
                    description: Whether the post field is required.
                    type: string
                isActive:
                    description: Whether the post field is active.
                    type: string
                sort:
                    description: The sort value of the post field.
                    type: string
                dateInserted:
                    description: When the post field was created.
                    type: string
                dateUpdated:
                    description: When the post field was last updated.
                    type: string
                insertUserID:
                    description: The user that created the post field.
                    type: string
                updateUserID:
                    description: The user that last updated the post field.
                    type: string
            required:
                - postFieldID
                - apiName
                - postTypeID
                - label
                - description
                - dataType
                - formType
                - visibility
                - displayOptions
                - dropdownOptions
                - isRequired
                - isActive
                - sort
                - dateInserted
                - dateUpdated
                - insertUserID
                - updateUserID
            type: object
