/**
 * @copyright 2009-2025 Vanilla Forums Inc.
 * @license Proprietary
 */

import { DraftRecordType, DraftStatus, IDraft } from "@vanilla/addon-vanilla/drafts/types";

export const mockDrafts: IDraft[] = [
    {
        draftID: 1,
        recordType: DraftRecordType.DISCUSSION,
        parentRecordID: 2,
        excerpt: "howdy",
        name: "Fresh Draft",
        attributes: {
            lastSaved: "",
            body: '[{"type":"p","children":[{"text":"howdy"}]}]',
            format: "rich2",
            draftType: "discussion",
            draftMeta: {
                tagIDs: [],
                pinLocation: "none",
            },
        },
        draftStatus: DraftStatus.DRAFT,
        breadCrumbs: [
            { name: "Category", url: "/category/1" },
            { name: "Subcategory", url: "/category/2" },
        ],
        dateScheduled: "2025-01-22T15:33:43+00:00",
        editUrl: "/edit/draftID=161",
        permaLink: "https://vanilla.local/discussion/1046/comment/161#Comment_161",
        insertUserID: 7,
        dateInserted: "2025-01-22T15:33:40+00:00",
        updateUserID: 7,
        dateUpdated: "2025-01-22T15:33:43+00:00",
    },
    {
        draftID: 3,
        recordType: DraftRecordType.COMMENT,
        parentRecordType: "discussion",
        parentRecordID: 4,
        attributes: {
            body: '[{"type":"p","children":[{"text":"eeeee test"}]}]',
            format: "rich2",
            draftType: "comment",
            draftMeta: {
                commentPath: "1395.1763.1764.1765",
                commentParentID: 1765,
                format: "rich2",
            },
            lastSaved: "2025-01-21T19:10:38.840Z",
        },
        excerpt: "eeeee test",
        name: "Draft Title",
        draftStatus: DraftStatus.DRAFT,
        breadCrumbs: [
            { name: "Category", url: "/category/1" },
            { name: "Subcategory", url: "/category/2" },
        ],
        dateScheduled: "2025-01-21T22:11:42+00:00",
        editUrl: "/edit/draftID=161",
        permaLink: "https://vanilla.local/discussion/1046/comment/161#Comment_161",
        insertUserID: 7,
        dateInserted: "2025-01-21T19:11:42+00:00",
        updateUserID: 7,
        dateUpdated: "2025-01-21T22:11:42+00:00",
    },
    {
        draftID: 5,
        recordType: DraftRecordType.COMMENT,
        parentRecordType: "discussion",
        parentRecordID: 6,
        attributes: {
            body: '[{"type":"p","children":[{"text":"eeeee test"}]}]',
            format: "rich2",
            draftType: "comment",
            draftMeta: {
                commentPath: "1395.1763.1764.1765",
                commentParentID: 1765,
                format: "rich2",
            },
            lastSaved: "2025-01-20T19:10:38.840Z",
        },
        excerpt: "eeeee test something else",
        name: "Draft Title 2",
        draftStatus: DraftStatus.DRAFT,
        breadCrumbs: [
            { name: "Category", url: "/category/1" },
            { name: "Subcategory", url: "/category/2" },
        ],
        dateScheduled: "2025-01-21T19:11:42+00:00",
        editUrl: "/edit/draftID=161",
        permaLink: "https://vanilla.local/discussion/1046/comment/161#Comment_161",
        failedReason: "some reson here",
        insertUserID: 7,
        dateInserted: "2025-01-21T19:11:42+00:00",
        updateUserID: 7,
        dateUpdated: "2025-01-21T19:11:42+00:00",
    },
    {
        draftID: 7,
        recordType: DraftRecordType.COMMENT,
        parentRecordType: "discussion",
        parentRecordID: 8,
        attributes: {
            body: '[{"type":"p","children":[{"text":"eeeee test"}]}]',
            format: "rich2",
            draftType: "comment",
            draftMeta: {
                commentPath: "1395.1763.1764.1765",
                commentParentID: 1765,
                format: "rich2",
            },
            lastSaved: "2025-01-21T19:10:38.840Z",
        },
        draftStatus: DraftStatus.ERROR,
        breadCrumbs: [
            { name: "Category", url: "/category/1" },
            { name: "Subcategory", url: "/category/2" },
        ],
        excerpt: "eeeee test something else hey hey",
        name: "",
        dateScheduled: "2025-01-21T19:11:42+00:00",
        editUrl: "/edit/draftID=161",
        permaLink: "https://vanilla.local/discussion/1046/comment/161#Comment_161",
        failedReason: "some reson here",
        insertUserID: 7,
        dateInserted: "2025-01-21T19:11:42+00:00",
        updateUserID: 7,
        dateUpdated: "2025-01-21T19:11:42+00:00",
    },
    {
        draftID: 9,
        recordType: DraftRecordType.DISCUSSION,
        attributes: {
            body: '[{"type":"p","children":[{"text":"eeeee test discussion"}]}]',
            format: "rich2",
            draftType: "comment",
            draftMeta: {
                commentPath: "1395.1763.1764.1765",
                commentParentID: 1765,
                format: "rich2",
            },
            lastSaved: "2025-01-21T19:10:38.840Z",
        },
        excerpt: "eeeee test something else hey hey",
        name: "",
        draftStatus: DraftStatus.ERROR,
        breadCrumbs: [
            { name: "Category", url: "/category/1" },
            { name: "Subcategory", url: "/category/2" },
        ],
        dateScheduled: "2025-01-21T02:11:42+00:00",
        editUrl: "/edit/draftID=161",
        permaLink: "https://vanilla.local/discussion/1046/comment/161#Comment_161",
        failedReason: "some reson here",
        insertUserID: 7,
        dateInserted: "2025-01-21T19:11:42+00:00",
        updateUserID: 7,
        dateUpdated: "2025-01-21T02:11:42+00:00",
    },
];
