name: "vanilla"
services:
    memcached:
        build:
            context: "./images/memcached"
        networks:
            "vanilla-network":
        container_name: memcached
        ports:
            - "11211:11211"
    vanilla-cloud-php:
        build:
            context: "./images/php"
            dockerfile: "./8.1/Dockerfile"
            args:
                WWWGROUP: "${WWWGROUP}"
                WWWUSER: "${WWWUSER}"
        container_name: "vanilla-cloud-php"
        networks:
            "vanilla-network":
        volumes:
            - "./images/nginx/certs:/usr/local/share/ca-certificates" # Mount self-signed certificates

            # Link our parents so other useful minimal repos like our sso stubs and embed stubs can work.
            # Also needed so relatively symlinked customer repositories work.
            - "../../:/srv/vanilla-repositories"

            # Needed in case our current directory is not named vanilla
            - "../:/srv/vanilla-repositories/vanilla:cached"

            # Not cached for consistency.
            - "../conf:/srv/vanilla-repositories/conf"
            - "../cache:/srv/vanilla-repositories/cache"

            # A few exclusions so that we don't have to sync some large directories.
            - "/srv/vanilla-repositories/vanilla/.git" # Don't sync this one.
            - "/srv/vanilla-repositories/vanilla/node_modules" # Don't sync this one.
            - "/srv/vanilla-repositories/vanilla/.yarn" # Don't sync this one either.

            # Specifically excluded because it runs in its own container.
            - /srv/vanilla-repositories/vanilla-queue-service
            - /srv/vanilla-repositories/vanilla-search-service

networks:
    vanilla-network:
        external: true
        driver: "bridge"
        name: "vanilla-network"
