name: "vanilla"
services:
    database:
        build:
            context: "./images/mysql"
        container_name: "database"
        ports:
            - "3306:3306"
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_DATABASE: vanilla_dev
        networks:
            - "vanilla-network"
        volumes:
            - "mysql8:/var/lib/mysql"
            - "logs-mysql8:/var/log/mysql"
    memcached:
        build:
            context: "./images/memcached"
        networks:
            - "vanilla-network"
        container_name: memcached
    php-fpm:
        build:
            context: "./images/php"
            dockerfile: "./8.1/Dockerfile"
            args:
                WWWGROUP: "${WWWGROUP}"
                WWWUSER: "${WWWUSER}"
        container_name: "php-fpm"
        networks:
            - "vanilla-network"
        volumes:
            - "./images/nginx/certs:/usr/local/share/ca-certificates" # Mount self-signed certificates

            # Link our parents so other useful minimal repos like our sso stubs and embed stubs can work.
            # Also needed so relatively symlinked customer repositories work.
            - "../../:/srv/vanilla-repositories"

            # Needed in case our current directory is not named vanilla
            - "../:/srv/vanilla-repositories/vanilla:cached"

            # Not cached for consistency.
            - "../conf:/srv/vanilla-repositories/conf"

            # A few exclusions so that we don't have to sync some large directories.
            - "/srv/vanilla-repositories/vanilla/.git" # Don't sync this one.
            - "/srv/vanilla-repositories/vanilla/node_modules" # Don't sync this one.
            - "/srv/vanilla-repositories/vanilla/.yarn" # Don't sync this one either.

            # Specifically excluded because it runs in its own container.
            - /srv/vanilla-repositories/vanilla-queue-service
            - /srv/vanilla-repositories/vanilla-search-service

volumes:
    mysql8:
    logs-mysql8:

networks:
    vanilla-network:
        external: true
        driver: "bridge"
        name: "vanilla-network"
