<?php if (!defined('APPLICATION')) exit();
// DO NOT EDIT THIS FILE. If you want to override the settings in this file then edit config.php.
// This is the global test application configuration file that sets up test default values for configuration settings.

// Disable Captcha checks for tests.
$Configuration['Garden']['Registration']['SkipCaptcha'] = true;