<?php if (!defined('APPLICATION')) exit();
/** This file was generated by the Locale Developer plugin on 2010-11-23 12:22:58 **/


$Definition['%1$s on %2$s'] = '%1$s on %2$s';
$Definition['%1$s Version %2$s'] = '%1$s Version %2$s';
$Definition['%s user(s) found.'] = '%s 人のユーザーが見つかりました。';

$Definition['(YYYY-mm-dd)'] = '(YYYY-mm-dd)';

$Definition['1 month after being sent'] = '1 month after being sent';
$Definition['1 week after being sent'] = '1 week after being sent';

$Definition['2 weeks after being sent'] = '2 weeks after being sent';

$Definition['<General Error>'] = '<General Error>';
$Definition['<strong>%1$s</strong> (%2$s) %3$s'] = '<strong>%1$s</strong> (%2$s) %3$s';
$Definition['<strong>The basic registration form requires</strong> that new users copy text from a "Captcha" image to keep spammers out of the site. You need an account at <a href="http://recaptcha.net/">recaptcha.net</a>. Signing up is FREE and easy. Once you have signed up, come back here and enter the following settings:'] = '<strong>The basic registration form requires</strong> that new users copy text from a "Captcha" image to keep spammers out of the site. You need an account at <a href="http://recaptcha.net/">recaptcha.net</a>. Signing up is FREE and easy. Once you have signed up, come back here and enter the following settings:';

$Definition['[%1$s] Membership Approved'] = '[%1$s] Membership Approved';

$Definition['_Locale'] = 'ロケール';

$Definition['A url-friendly version of the category name for better SEO.'] = 'A url-friendly version of the category name for better SEO.';
$Definition['Action'] = 'アクション';
$Definition['Activate'] = 'アクティベート';
$Definition['Add'] = '追加';
$Definition['Add Message'] = 'メッセージを追加';
$Definition['Add Route'] = 'ルートを追加';
$Definition['Add User'] = 'ユーザーを追加';
$Definition['Addons'] = 'アドオン';
$Definition['Administrator'] = '管理者';
$Definition['Advanced'] = '高度な設定';
$Definition['Advanced Forum Settings'] = 'Advanced Forum Settings';
$Definition['All '] = 'すべて ';
/*
$Definition['All <span>16</span>'] = 'すべて <span>16</span>';
$Definition['All <span>2</span>'] = 'すべて <span>2</span>';
*/
$Definition['Announce'] = 'アナウンス';
$Definition['Appearance'] = '外観';
$Definition['Applicant'] = '申請者';
$Definition['Applicants'] = '申請者';
$Definition['Application'] = 'アプリケーション';
$Definition['Application ID'] = 'アプリケーション ID';
$Definition['Application Secret'] = 'Application Secret';
$Definition['ApplicationHelp'] = 'アプリケーションは、あなたのサイトに大規模な機能群を追加します。<br />%s フォルダに追加されたアプリケーションを、ここで有効化または無効化できます。';
$Definition['Applications'] = 'アプリケーション';
$Definition['Approve'] = '承認';
$Definition['Archive Discussions'] = '過去のスレッド';
$Definition['Are you sure you want to do that?'] = 'Are you sure you want to do that?';
$Definition['at'] = 'at';
$Definition['Authentication'] = '認証';

$Definition['Banned'] = '利用禁止';
$Definition['Banner'] = 'バナー';
$Definition['Banner Logo'] = 'バナー ロゴ';
$Definition['Banner Title'] = 'バナー タイトル';

$Definition['Cancel'] = 'キャンセル';

$Definition['Capture definitions throughout the site. You must visit the pages in the site in order for the definitions to be captured. The captured definitions will be put in the <code>captured.php</code> and <code>captured_admin.php</code>.'] = 'このサイトの定義文を収集します。あなたは定義文を収集したいページを順番に訪れる必要があります。収集された定義文は <code>captured.php</code> と <code>captured_admin.php</code> に出力されます。';
$Definition['Capture locale pack changes.'] = 'ロケール デベロッパーと、指定されたロケール パックとの相違点を収集します。結果は <code>changes.php</code> ファイルに出力されます。';
$Definition['Categories'] = 'カテゴリ';
$Definition['Categories are used to help organize discussions.'] = 'カテゴリはスレッドをまとめるのに役立ちます。ドラッグ &amp; ドロップで、並べ替えやネストもできます。';
$Definition['Category'] = 'カテゴリ';
$Definition['Category Url:'] = 'カテゴリ URL:';
$Definition['Change the way that new users register with the site.'] = 'Change the way that new users register with the site.';
$Definition['Check all permissions that apply for each role'] = '以下の役割に適用する権限すべてにチェックを入れてください';
$Definition['Check all roles that apply to this user:'] = 'このユーザーに適用する役割にすべてチェックを入れてください:';
$Definition['Choose a locale pack'] = 'ロケール パックを選んでください';
$Definition['Choose and configure your forum\'s authentication scheme.'] = 'Choose and configure your forum\'s authentication scheme.';
$Definition['Choose who can send out invitations to new members:'] = 'Choose who can send out invitations to new members:';
$Definition['Close'] = 'Close';
$Definition['comment(s)'] = '件のレスポンス';
$Definition['Comments'] = 'コメント';
$Definition['Comments per Page'] = '1 ページに表示する最大レス数';
$Definition['Configure an Authenticator'] = 'Configure an Authenticator';
$Definition['Confirm'] = '確認';
$Definition['Confirm Email'] = '電子メールで通知する';
$Definition['Consumer Key'] = 'Consumer Key';
$Definition['Consumer Secret'] = 'Consumer Secret';
$Definition['Conversation Messages'] = 'Conversation Messages';
$Definition['Copy'] = 'コピー';
$Definition['Copy locale pack.'] = 'ロケール パックからロケール デベロッパーに定義文をコピーします。定義文は <code>copied.php</code> ファイルに出力されます。';
$Definition['Current Authenticator'] = 'Current Authenticator';
$Definition['Current Theme'] = '現在のテーマ';
$Definition['Customize your Public Profile'] = '公開プロフィールをカスタマイズ';

$Definition['Dashboard'] = 'ダッシュボード';
$Definition['Date.DefaultDayFormat'] = '%B %e';
$Definition['Date.DefaultTimeFormat'] = '%l:%M%p';
$Definition['Decline'] = 'Decline';
$Definition['Description'] = '説明';
$Definition['Disable'] = '無効化';
$Definition['Disable Google Sign In'] = 'Google アカウントでのログインを無効化';
$Definition['Disable OpenID'] = 'OpenID を無効化';
$Definition['Disabled '] = '無効 ';
/*
$Definition['Disabled <span>0</span>'] = '無効 <span>0</span>';
$Definition['Disabled <span>10</span>'] = '無効 <span>10</span>';
$Definition['Disabled <span>11</span>'] = '無効 <span>11</span>';
$Definition['Disabled <span>12</span>'] = '無効 <span>12</span>';
$Definition['Disabled <span>9</span>'] = '無効 <span>9</span>';
*/
$Definition['Discussion & Comment Editing'] = 'スレッド & レスポンス編集';
$Definition['discussion(s)'] = '件のスレッド';
$Definition['Discussions'] = 'スレッド';
$Definition['Discussions per Page'] = '1 ページに表示する最大スレッド数';
$Definition['dot'] = 'ドット';

$Definition['Edit'] = '編集';
$Definition['edit'] = '編集';
$Definition['Edit Category'] = 'カテゴリを編集';
$Definition['Edit User'] = 'ユーザーを編集';
$Definition['EditContentTimeout.Notes'] = 'Note: If a user is in a role that has permission to edit content, those permissions will override any value selected here.';
$Definition['Email'] = 'メール アドレス';
$Definition['Email sent from the application will be addressed from the following name and address'] = 'Email sent from the application will be addressed from the following name and address';
$Definition['Email visible to other users'] = '他のメンバーにメール アドレスを公開する';
$Definition['EmailMembershipApproved'] = 'Hello %1$s,

You have been approved for membership. Sign in now at the following link:

  %2$s
  
Have a great day!';
$Definition['Enable'] = '有効化';
$Definition['Enable Google Sign In'] = 'Google アカウントでのログインを有効化';
$Definition['Enable OpenID'] = 'OpenID を有効化';
$Definition['Enabled '] = '有効 ';
/*
$Definition['Enabled <span>2</span>'] = '有効 <span>2</span>';
$Definition['Enabled <span>4</span>'] = '有効 <span>4</span>';
$Definition['Enabled <span>5</span>'] = '有効 <span>5</span>';
$Definition['Enabled <span>6</span>'] = '有効 <span>6</span>';
$Definition['Enabled <span>7</span>'] = '有効 <span>7</span>';
*/
$Definition['Existing members send invitations to new members.'] = 'Existing members send invitations to new members.';

$Definition['Facebook Connect allows users to sign in using their Facebook account.'] = 'Facebook Connect allows users to sign in using their Facebook account. <b>You must register your application with Facebook for this plugin to work.</b>';
$Definition['Facebook Settings'] = 'Facebook Settings';
$Definition['First Visit'] = '訪問開始';
$Definition['For more help on localization check out the page <a href="%s">here</a>.'] = 'For more help on localization check out the page <a href="%s">here</a>.';
$Definition['Forum Settings'] = 'フォーラム設定';

$Definition['Garden.Email.SupportAddress'] = 'Support email';
$Definition['Garden.Import.Description'] = 'Use this page to import data from another forum that was exported using Vanilla\'s exporter. For more information <a href="%s">see our importing documentation</a>.';
$Definition['Garden.Import.InputInstructions'] = 'Enter the email and password of the admin user from the data being imported.';
$Definition['Garden.Import.Overwrite.Description'] = 'Warning: All data in this forum will be overwritten.';
$Definition['Generate'] = '生成';
$Definition['Generate Password'] = 'パスワードを生成';
$Definition['Go'] = '検索';
$Definition['Google Sign In Settings'] = 'Google サインイン 設定';
$Definition['Guest'] = 'ゲスト';

$Definition['here'] = 'ここ';

$Definition['Import'] = 'インポート';
$Definition['Inbox'] = '受信トレイ';
$Definition['Information'] = '情報';
$Definition['Internal'] = 'Internal';
$Definition['Invitations can be sent from users\' profile pages.'] = 'When you use registration by invitation users will have a link called <a href="%s" class="Popup">My Invitations</a> on their profile pages.';
$Definition['Invitations per month'] = 'Invitations per month';
$Definition['Invitations will expire'] = 'Invitations will expire';
$Definition['It is a good idea to keep the maximum number of characters allowed in a comment down to a reasonable size.'] = '投稿できる文字数の上限を適度な数値に抑えることを、推奨します。';

$Definition['Key Type'] = 'Key Type';
$Definition['Key Value'] = 'Key Value';

$Definition['Last Active'] = 'Last Active';
$Definition['Last Visit'] = '最終訪問';
$Definition['Locale'] = 'ja-JP';
$Definition['Locale Developer'] = 'ロケール デベロッパー';
$Definition['Locale Developer Settings %s.'] = 'Locale Developer Settings %s.';
$Definition['Locale info file settings.'] = '<p>When you generate the zip file you can set the information for the locale below.</p> <p>You can download a zip of the locale pack by clicking <a href="%s">here</a>.</p>';
$Definition['Locale Key (Folder)'] = 'ロケール キー (フォルダ名)';
$Definition['Locale Name'] = 'ロケール名';
$Definition['Locales'] = 'ロケール';
$Definition['Locales are in your %s folder.'] = 'ロケールは、あなたのサイトを既定以外の言語で表示できるようにします。%s フォルダに追加されたロケールを、ここで有効化または無効化できます。';
$Definition['Location'] = '場所';

$Definition['Manage Applicants'] = '申請者管理';
$Definition['Manage Applications'] = 'アプリケーション管理';
$Definition['Manage Categories'] = 'カテゴリ管理';
$Definition['Manage Messages'] = 'メッセージ管理';
$Definition['Manage Plugins'] = 'プラグイン管理';
$Definition['Manage Roles & Permissions'] = 'Manage Roles & Permissions';
$Definition['Manage Routes'] = 'ルート管理';
$Definition['Manage Spam'] = 'スパム管理';
$Definition['Manage Themes'] = 'テーマ管理';
$Definition['Manage Users'] = 'ユーザー管理';
$Definition['Manage your Plugins'] = 'Manage your Plugins';
$Definition['Max Comment Length'] = '最大投稿文字数';
$Definition['Member'] = 'メンバー';
$Definition['Message'] = 'メッセージ';
$Definition['Messages'] = 'メッセージ';
$Definition['Messages can appear anywhere in your application.'] = 'メッセージはサイトのどこにでも表示でき、ユーザーにニュースやイベントを通知するために使われます。Use this page to re-organize your messages by dragging them up or down.';
$Definition['Method'] = 'Method';
$Definition['minute(s)'] = '分間';
$Definition['Moderator'] = 'モデレータ';

$Definition['Name'] = '名前';
$Definition['never'] = 'never';
$Definition['New comments in the last day'] = 'New comments in the last day';
$Definition['New comments in the last week'] = 'New comments in the last week';
$Definition['New conversations in the last day'] = 'New conversations in the last day';
$Definition['New conversations in the last week'] = 'New conversations in the last week';
$Definition['New discussions in the last day'] = 'New discussions in the last day';
$Definition['New discussions in the last week'] = 'New discussions in the last week';
$Definition['New messages in the last day'] = 'New messages in the last day';
$Definition['New messages in the last week'] = 'New messages in the last week';
$Definition['New Password'] = '新しいパスワード';
$Definition['New users are reviewed and approved by an administrator (that\'s you!).'] = 'New users are reviewed and approved by an administrator (that\'s you!).';
$Definition['New users fill out a simple form and are granted access immediately.'] = 'New users fill out a simple form and are granted access immediately.';
$Definition['New users in the last day'] = 'New users in the last day';
$Definition['New users in the last week'] = 'New users in the last week';
$Definition['None'] = 'None';
$Definition['Not Authorized (401)'] = 'Not Authorized (401)';
$Definition['Not Found (404)'] = '見つかりません (404)';

$Definition['OK'] = 'OK';
$Definition['Okay'] = 'Okay';
$Definition['Only Allow Each User To Post'] = '1 ユーザーにつき投稿可能な件数';
$Definition['OpenID Settings'] = 'OpenID 設定';
$Definition['Options'] = 'オプション';
$Definition['Or Spamblock For'] = '違反時のスパムブロック時間';
$Definition['Organize your Categories'] = 'Organize your Categories';
$Definition['Other Themes'] = '他のテーマ';
$Definition['Outgoing Email'] = 'Outgoing Email';

$Definition['Page'] = '表示対象';
$Definition['Panel Box'] = 'パネル ボックス';
$Definition['Password'] = 'パスワード';
$Definition['Password Options'] = 'パスワード オプション';
$Definition['Permanent (301)'] = 'Permanent (301)';
$Definition['Please choose an authenticator to configure.'] = 'Please choose an authenticator to configure.';
$Definition['Plugin'] = 'プラグイン';
$Definition['PluginHelp'] = 'プラグインは、あなたのサイトに拡張機能を追加します。<br />%s フォルダに追加されたプラグインを、ここで有効化または無効化できます。';
$Definition['Plugins'] = 'プラグイン';
$Definition['Position'] = '表示位置';
$Definition['Prevent spam on your forum by limiting the number of discussions &amp; comments that users can post within a given period of time.'] = 'スパムを防ぐため、ユーザーが一定時間内に作成できるスレッドおよび投稿できるレスポンスの数を制限できます。';
$Definition['Private Key'] = 'プライベートキー';
$Definition['Public Key'] = '公開キー';

$Definition['Recently Active Users'] = 'Recently Active Users';
$Definition['Refresh Comments'] = 'Refresh Comments';
$Definition['Registration'] = '登録';
$Definition['Remove'] = '削除';
$Definition['Remove locale developer files.'] = 'ロケール デベロッパーのファイルを削除して、変更をリセットします。';
$Definition['Requires: '] = '動作要件: ';
$Definition['Reset Password'] = 'パスワードをリセット';
$Definition['Reset password and send email notification to user'] = 'Reset password and send email notification to user';
$Definition['Reveal Password'] = 'パスワードを表示';
$Definition['Role'] = '役割';
$Definition['Roles & Permissions'] = '役割と権限';
$Definition['Roles determine user\'s permissions.'] = 'Every user in your site is assigned to at least one role. Roles are used to determine what the users are allowed to do.';
$Definition['Route'] = 'ルート';
$Definition['Route Expression'] = 'Route Expression';
$Definition['Routes'] = 'Routes';
$Definition['Routes can be used to redirect users to various parts of your site depending on the url.'] = 'ルートは URL に基づきユーザーを適切なページへリダイレクトするために使用されます。';

$Definition['Save'] = '保存';
$Definition['Search'] = '検索';
$Definition['seconds'] = '秒間';
$Definition['Select the file to import'] = 'インポートするファイルを選択してください';
$Definition['Settings'] = '設定';
$Definition['Sign Out'] = 'ログアウト';
$Definition['Sink'] = 'Sink';
$Definition['SMTP Host'] = 'SMTP サーバー';
$Definition['SMTP Password'] = 'SMTP パスワード';
$Definition['SMTP Port'] = 'SMTP ポート';
$Definition['SMTP Security'] = 'SMTP セキュリティ';
$Definition['SMTP User'] = 'SMTP ユーザー';
$Definition['Spam'] = 'スパム';
$Definition['Start your First Discussion'] = '最初のスレッドを立てる';

$Definition['Target'] = '対象';
$Definition['Temporary (302)'] = '一時的 (302)';
$Definition['The %s Authenticator does not have any custom configuration options.'] = 'The %s Authenticator does not have any custom configuration options.';
$Definition['The addon could not be enabled because it generated a fatal error: <pre>%s</pre>'] = 'The addon could not be enabled because it generated a fatal error: <pre>%s</pre>';
$Definition['The banner logo appears at the top of your forum.'] = 'バナー ロゴは、フォーラムの先頭に表示されます。';
$Definition['The banner title appears on the top-left of every page. If a banner logo is uploaded, it will replace the banner title on user-facing forum pages.'] = 'バナー タイトルは、すべてのページの左上に表示されます。バナー ロゴをアップロードすると、バナー タイトルは置き換えられます。';
$Definition['The file failed to upload.'] = 'The file failed to upload.';
$Definition['ThemeHelp'] = 'テーマはあなたのサイトの外観を変更します。<br />%s フォルダに追加されたテーマを、ここで有効化できます。';
$Definition['Themes'] = 'テーマ';
$Definition['There are currently no applicants.'] = '申請者はいません。';
$Definition['This plugin allows users to sign in with OpenID. <b>Make sure you click Settings after enabling this plugin to enable OpenID signin</b>.'] = 'This plugin allows users to sign in with OpenID. <b>Make sure you click Settings after enabling this plugin to enable OpenID signin</b>.';
$Definition['This plugin allows users to sign in with their Google accounts. <b>Make sure you click Settings after enabling this plugin to enable Google signin</b>.'] = 'This plugin allows users to sign in with their Google accounts. <b>Make sure you click Settings after enabling this plugin to enable Google signin</b>.';
$Definition['This plugin helps locale package development.'] = 'このプラグインは、ロケール パッケージの開発を助けます。The plugin keeps a working locale pack at <code>%s</code>.';
$Definition['Tools'] = 'ツール';
$Definition['Transport error: %s'] = 'A fatal error occurred while processing the request.<br />The server returned the following response: %s';
$Definition['Twitter Connect allows users to sign in using their Twitter account.'] = 'Twitter Connect allows users to sign in using their Twitter account. <b>You must register your application with Twitter for this plugin to work.</b>';
$Definition['Twitter Settings'] = 'Twitter Settings';
$Definition['Type'] = 'Type';

$Definition['Unlimited'] = '無制限';
$Definition['Upload'] = 'アップロード';
$Definition['Url'] = 'URL';
$Definition['User'] = 'ユーザー';
$Definition['User Registration Settings'] = 'ユーザー登録設定';
$Definition['Username'] = 'ユーザー名';
$Definition['Users'] = 'ユーザー';

$Definition['ValidateRequired'] = '%s is required.';
$Definition['Vanilla.Archive.Description'] = '特定の日付より古いスレッドをアーカイブ化できます。アーカイブ化されたスレッドは事実上 閉じられ、新しいレスを受け付けなくなります。';
$Definition['Version'] = 'バージョン';
$Definition['Version %s'] = 'バージョン %s';
$Definition['version %s'] = 'バージョン %s';
$Definition['View'] = 'ビュー';
$Definition['Visit Site'] = 'サイトへ移動';

$Definition['Warning'] = '警告';
$Definition['We will attempt to use the local mail server to send email by default. If you want to use a separate SMTP mail server, you can configure it below.'] = 'We will attempt to use the local mail server to send email by default. If you want to use a separate SMTP mail server, you can configure it below.';
$Definition['Welcome Aboard!'] = 'ようこそ！';
$Definition['What\'s the Buzz?'] = 'What\'s the Buzz?';
$Definition['Within'] = '制限時間';

$Definition['You can always use your password at<a href="%1$s">%1$s</a>.'] = 'If you are ever locked out of your forum you can always log in using your original Vanilla email and password at <a href="%1$s">%1$s</a>';
$Definition['You can place files in your /uploads folder.'] = 'If your file is too
		large to upload directly to this page you can place it in your /uploads
		folder. Make sure the filename begins with the word <b>export</b> and ends
		with one of <b>.txt, .gz</b>.';
$Definition['You cannot disable the %1$s plugin because the %2$s plugin requires it in order to function.'] = 'You cannot disable the %1$s plugin because the %2$s plugin requires it in order to function.';
$Definition['You cannot disable the OpenID plugin because the GoogleSignIn plugin requires it in order to function.'] = 'You cannot disable the OpenID plugin because the GoogleSignIn plugin requires it in order to function.';
$Definition['Your changes have been saved.'] = '変更を保存しました。';
$Definition['Your settings have been saved.'] = '設定を保存しました。';

/** 以下は、オリジナルに無かったエントリです **/
$Definition['Search by user or role.'] = 'ユーザー名または役割 (管理者:<input type="text" value="Administrator" size="10" onclick="this.select()" />, 申請者:<input type="text" value="Applicant" size="6" onclick="this.select()" />, 利用禁止:<input type="text" value="Banned" size="5" onclick="this.select()" />, ゲスト:<input type="text" value="Guest" size="3" onclick="this.select()" />, メンバー:<input type="text" value="Member" size="5" onclick="this.select()" />, モデレータ:<input type="text" value="Moderator" size="7" onclick="this.select()" />) で検索します。';
$Definition['Add Category'] = 'カテゴリを追加';
$Definition['Don\'t use Categories'] = 'カテゴリを使用しない';
$Definition['Role Name'] = '役割名';
$Definition['Edit Role'] = '役割を編集';
$Definition['Manage'] = '管理';
$Definition['Allow'] = '許可';
$Definition['Check all permissions that apply to this role:'] = '以下の役割に適用する権限すべてにチェックを入れてください:';
$Definition['SignIn'] = 'ログイン';
$Definition['Profiles'] = 'プロフィール';
$Definition['Authors cannot edit their posts'] = '投稿者は自分の投稿を編集できません';
$Definition['Authors can edit for 5 minutes after posting'] = '投稿者は投稿後 5 分以内なら編集できます';
$Definition['Authors can edit for 15 minutes after posting'] = '投稿者は投稿後 5 分以内なら編集できます';
$Definition['Authors can edit for 30 minutes after posting'] = '投稿者は投稿後 5 分以内なら編集できます';
$Definition['Authors can edit for 1 day after posting'] = '投稿者は投稿後 1 日以内なら編集できます';
$Definition['Authors can edit for 1 week after posting'] = '投稿者は投稿後 1 週間以内なら編集できます';
$Definition['Authors can edit for 1 month after posting'] = '投稿者は投稿後 1 ヶ月間以内なら編集できます';
$Definition['Authors can always edit their posts'] = '投稿者はいつでも自分の投稿を編集できます';
$Definition['Get more information on creating custom routes'] = '独自のルートを作成するなら、詳しくはこちら';
$Definition['Get More Applications'] = '他のアプリケーション';
$Definition['Get More Themes'] = '他のテーマ';
$Definition['Get More Plugins'] = '他のプラグイン';
$Definition['By %s'] = '作成者: %s';
$Definition['Need More Help?'] = '参考情報';
$Definition['Theming Overview'] = 'テーマの概要 (英語)';
$Definition['Quick-Start Guide to Creating Themes for Vanilla'] = 'テーマ作成のためのクイック スタート ガイド (英語)';
$Definition['Allow users to dismiss this message'] = 'このメッセージを閉じることをユーザーに許可する';
$Definition['Enable this message'] = 'このメッセージを有効化する';
$Definition['Saved'] = '保存しました';
$Definition['Organize Categories'] = 'カテゴリ構成';
$Definition['Category Page Layout'] = 'カテゴリのページ レイアウト';
$Definition['View Page'] = 'ページを表示';
$Definition['Did You Know?'] = 'ご存知ですか？';
$Definition['You can make the categories page your homepage.'] = 'カテゴリ一覧のページを<a href="%s">こちら</a>でホームページとして設定できます。';
$Definition['Make sure you click View Page'] = '<a href="%s">ページを表示</a>をクリックすると、保存後にカテゴリ ページがどのように見えるかを確認することができます。';
$Definition['Drag and drop the categories below to sort and nest them.'] = 'カテゴリを並べ替えたりネストするには、この下のカテゴリをドラッグ &amp; ドロップしてください。';
$Definition['Configure how nested categories are displayed to users.'] = 'ネストされたカテゴリをどのように表示するか、設定してください。';
$Definition['Vanilla.Categories.MaxDisplayDepth'] = 'ネストされたカテゴリが次の条件に合致する場合は、カンマ区切りのリストとして表示されます: %1$s';
$Definition['Display root categories as headings.'] = 'ルート カテゴリを見出しとして表示する。';
$Definition['Do not display the categories in the side panel.'] = 'カテゴリ一覧をサイドパネルに表示しない。';
$Definition['more than one level deep'] = 'カテゴリ一覧をサイドパネルに表示しない。';
$Definition['Managing Categories'] = 'カテゴリの管理 (英語)';
$Definition['Adding & Editing Categories'] = 'カテゴリの追加と編集 (英語)';
$Definition['Homepage'] = 'ホームページ';
$Definition['Configuring Vanilla\'s Homepage'] = 'Vanilla のホームページ設定 (英語)';
$Definition['Change the look of All Categories'] = '<b>すべてのカテゴリ</b> ページの外観は<a href="%s">こちら</a>から変更できます。';
$Definition['Changing the Discussions Menu Link'] = 'ディスカッション メニュー リンクの変更 (英語)';
$Definition['Use the content at this url as your homepage.'] = '"ホームページ" は <strong>%s</strong> にアクセスしたときに表示されます。既定では "すべてのスレッド" がホームページになっていますが、この設定は自由に変更できます。以下は代表的なオプションです:';
$Definition['All Categories'] = 'すべてのカテゴリ';
$Definition['Categories &amp; Discussions'] = 'カテゴリ &amp; スレッド';
$Definition['Enter the url to the page you would like to use as your homepage:'] = 'ホームページに設定したいページの URL を入力してください:';
$Definition['TermsOfService'] = '利用規約';
$Definition['TermsOfServiceText'] = "
   <p>このサービスを利用する時点で、以下の規約に同意したものとみなします。
   本コミュニティにおいて、中傷(虚偽かどうかに関わらず)、嘘、暴言、罵倒、悪態、
   嫌がらせ、わいせつ表現、冒涜表現、性的表現、脅迫、プライバシーの侵害、
   あるいは違法な内容は投稿できません。あなた自身が著作権者である場合を除き、
   著作権によって保護された内容は投稿できません。</p>
   
   <p>本コミュニティはまた、あなたの投稿によって法律問題や訴訟が発生した場合、
   個人情報 (あるいは何であれ知り得た情報) を提供する権利を有するものとします。
   本ウェブ サイトへのアクセスは、いかなるインターネット プロトコルによるもので
   あれ、記録されます。</p>
   
   <p>広告、チェーンレター、マルチ商法、セールスの勧誘は、本コミュニティにおいて
   不適切な行為とみなされます。</p>
   
   <p>本コミュニティは、理由のいかんに関わらず いかなるコンテンツをも削除する
   権利を有するものとします。また理由のいかんに関わらず いかなる会員資格をも
   停止する権利を有するものとします。</p>
   
   <p>このサービスを利用するには、13 歳以上である必要があります。</p>
";
$Definition['Version 2 Installer'] = 'バージョン 2 インストーラ';
$Definition['Database Host'] = 'データベース ホスト';
$Definition['Database Name'] = 'データベース名 <span style="font-size:13px;">※ あらかじめ作成しておく必要があります。</span>';
$Definition['Database User'] = 'データベース ユーザ';
$Definition['Database Password'] = 'データベース パスワード';
$Definition['You are missing Vanilla\'s .htaccess file.'] = 'Vanilla の <b>.htaccess</b> ファイルが見つかりません。ファイルのアップロードに FTP を使用している場合、このファイルは非表示になっていてコピーされなかったかもしれません。続行する前に、<b>.htaccess</b> ファイルがコピー済みであることを確認してください。';
$Definition['The database user you specified does not have permission to access the database. Have you created the database yet? The database reported: <code>%s</code>'] = '指定されたデータベース ユーザには、このデータベースへのアクセス権がありません。データベースは作成済みですか？　データベースの報告は次の通りです: <code>%s</code>';
$Definition['Install Vanilla without a .htaccess file.'] = '.htaccess ファイル無しで Vanilla をインストールします。';
$Definition['Yes, the following information can be changed later.'] = 'ここから下の情報は、後で変更できます。';
$Definition['Application Title'] = 'アプリケーション タイトル';
$Definition['Admin Email'] = '管理者の E メール';
$Definition['Admin Username'] = '管理者のユーザ名';
$Definition['Admin Password'] = '管理者のパスワード';
$Definition['Confirm Password'] = '確認用パスワード(再入力)';
$Definition['Continue &rarr;'] = '続行 &rarr;';
$Definition['Failed to connect to the database with the username and password you entered. Did you mistype them? The database reported: <code>%s</code>'] = '入力されたユーザ名とパスワードでは、データベースに接続できません。入力ミスの可能性はありませんか？　データベースの報告は次の通りです: <code>%s</code>';
$Definition['It appears as though the database you specified does not exist yet. Have you created it yet? Did you mistype the name? The database reported: <code>%s</code>'] = '指定されたデータベースが まだ作成されていないようです。データベースは作成済みですか？　あるいはデータベース名が間違っている可能性はありませんか？　データベースの報告は次の通りです: <code>%s</code>';
$Definition["Are you sure you've entered the correct database host name? Maybe you mistyped it? The database reported: <code>%s</code>"] = 'データベース ホスト名は正しく入力されましたか？　入力ミスの可能性はありませんか？　データベースの報告は次の通りです: <code>%s</code>';
$Definition['UsernameError'] = 'ユーザー名には 3～20 文字の英数字とアンダースコアのみ使用できます。';
$Definition['You must specify an admin username.'] = '管理者のユーザー名は省略できません。';
$Definition['You must specify an admin password.'] = '管理者のパスワードは省略できません。';
$Definition['You are running PHP version %1$s. Vanilla requires PHP %2$s or greater. You must upgrade PHP before you can continue.'] = 'PHP のバージョン %1$s 上で実行中ですが、Vanilla には PHP %2$s 以上が必要です。続行する前に PHP をアップグレードしてください。';
$Definition['You must have the PDO module enabled in PHP in order for Vanilla to connect to your database.'] = 'Vanilla があなたのデータベースに接続できるよう、PHP の PDO モジュールを有効にしてください。';
$Definition['You must have the MySQL driver for PDO enabled in order for Vanilla to connect to your database.'] = 'Vanilla があなたのデータベースに接続できるよう、MySQL ドライバ for PDO を有効にしてください。';
$Definition['Some folders don\'t have correct permissions.'] = '<p>適切なアクセス権が設定されていないフォルダがあります。</p><p>FTP クライアントかコマンド ラインを使って、vanilla のインストール フォルダに次のアクセス権を設定してください:</p>';
$Definition['Your configuration file does not have the correct permissions. PHP needs to be able to read and write to this file: <code>%s</code>'] = '設定ファイルに適切なアクセス権が設定されていません。PHP はこのファイルを読み書きする必要があります: <code>%s</code>';
//$Definition[''] = '';
