<?php if (!defined('APPLICATION')) {
    exit();
      }

// DO NOT EDIT THIS FILE
// All of the settings defined here can be overridden in the /conf/*.php files.

$Configuration['Garden']['Profile']['EditUsernames'] = false;
$Configuration['Garden']['Activities']['PerPage'] = 30;
