<?php if (!defined('APPLICATION')) exit();

/** 
 * Dashboard Application
 * 
 * Default configuration settings. These should never be edited for customization,
 * but rather overridden in config.php
 * 
 * @copyright 2003 Vanilla Forums, Inc
 * @license http://www.opensource.org/licenses/gpl-2.0.php GPL
 * @package Garden
 * @since 2.0
 */


// DO NOT EDIT THIS FILE
// All of the settings defined here can be overridden in the /conf/*.php files.

$Configuration['Garden']['Profile']['EditUsernames'] = FALSE;
