<?php return [
    'name' => 'Little Emoji',
    'author' => 'Todd Burry',
    'description' => 'Inspired by the the original 15px smileys seen on forums and still favored by emoticon enthusiasts everywhere. Now with anti-aliasing technology.',
    'format' => '<img class="emoji" src="{src}" title="{name}" alt="{name}" srcset="{dir}/{basename}@2x{ext} 2x" />',
    'icon' => 'little-icon.png',
    'emoji' =>
        [
            -1 => '-1.png',
            '+1' => '+1.png',
            'angry' => 'angry.png',
            'anguished' => 'anguished.png',
            'awesome' => 'awesome.png',
            'bawling' => 'bawling.png',
            'bleep_bloop' => 'bleep_bloop.png',
            'blush' => 'blush.png',
            'chuffed' => 'chuffed.png',
            'confounded' => 'confounded.png',
            'confused' => 'confused.png',
            'cry' => 'cry.png',
            'dizzy' => 'dizzy.png',
            'eh' => 'eh.png',
            'expressionless' => 'expressionless.png',
            'fearful' => 'fearful.png',
            'frown' => 'frown.png',
            'glasses' => 'glasses.png',
            'grin' => 'grin.png',
            'heart' => 'heart.png',
            'heartbreak' => 'heartbreak.png',
            'hurrah' => 'hurrah.png',
            'innocent' => 'innocent.png',
            'lol' => 'lol.png',
            'love' => 'love.png',
            'mrgreen' => 'mrgreen.png',
            'naughty' => 'naughty.png',
            'neutral' => 'neutral.png',
            'no_mouth' => 'no_mouth.png',
            'open_mouth' => 'open_mouth.png',
            'pleased' => 'pleased.png',
            'proud' => 'proud.png',
            'rage' => 'rage.png',
            'scream' => 'scream.png',
            'silenced' => 'silenced.png',
            'skull' => 'skull.png',
            'smile' => 'smile.png',
            'smiley' => 'smiley.png',
            'star' => 'star.png',
            'sunglasses' => 'sunglasses.png',
            'surprised' => 'surprised.png',
            'sweat' => 'sweat.png',
            'tongue' => 'tongue.png',
            'unamused' => 'unamused.png',
            'waving' => 'waving.png',
            'wink' => 'wink.png',
            'winky' => 'winky.png',
        ],
    'aliases' =>
        [
            ':)' => 'smile',
            ':D' => 'grin',
            ':(' => 'frown',
            ';)' => 'wink',
            ':\\' => 'confused',
            ':/' => 'confused',
            ':o' => 'open_mouth',
            ':s' => 'confounded',
            ':p' => 'tongue',
            ':\'(' => 'cry',
            ':|' => 'neutral',
            'D:' => 'anguished',
            'B)' => 'sunglasses',
            'o:)' => 'innocent',
            '<3' => 'heart',
            '>:)' => 'naughty',
            'O.o' => 'surprised',
            'o.O' => 'eh',
            '8-)' => 'glasses',
            '=)' => 'smiley',
            '>_<' => 'rage',
            ':3' => 'blush',
        ],
    'editor' =>
        [
            ':)' => 'smile',
            ':D' => 'smiley',
            ';)' => 'wink',
            ':o' => 'open_mouth',
            ':p' => 'tongue',
            ':(' => 'frown',
            'B)' => 'sunglasses',
            'O.o' => 'surprised',
            ':3' => 'blush',
            '<3' => 'heart',
            'o:)' => 'innocent',
            '>:)' => 'naughty',
        ],
    'archive' =>
        [
            'broken_heart' => 'heartbreak.png',
            'dizzy_face' => 'dizzy.png',
            'grinning' => 'grin.png',
            'heart_eyes' => 'love.png',
            'neutral_face' => 'neutral.png',
            'smiling_imp' => 'naughty.png',
            'sob' => 'bawling.png',
            'stuck_out_tongue' => 'tongue.png',
        ],
    'minSize' =>
        [
            'w' => 15,
            'h' => 18,
        ],
    'maxSize' =>
        [
            'w' => 22,
            'h' => 18,
        ],
    'sizes' =>
        [
            0 => 1,
            1 => 2,
        ],
];
