<?php if (!defined('APPLICATION')) exit();
// DO NOT EDIT THIS FILE
// All of the settings defined here can be overridden in the /conf/config.php file.
$Configuration['Update']['Automatic']['Check'] = TRUE;
$Configuration['Update']['Automatic']['Download'] = TRUE;

$Configuration['Update']['Local']['Scratch'] = PATH_CACHE.DS.'Updates'.DS.'scratch';
$Configuration['Update']['Local']['Backups'] = PATH_UPLOADS.DS.'Updates'.DS.'restorepoints';
$Configuration['Update']['Local']['Downloads'] = PATH_UPLOADS.DS.'Updates'.DS.'archives';

$Configuration['Update']['Local']['TaskListKey'] = 'UpdateTaskList-progress';

$Configuration['Update']['Remote']['Repository'] = 'http://www.vanillaforums.org';
$Configuration['Update']['Remote']['Addon'] = 'vanilla-core';

$Configuration['Update']['Remote']['RPC']['Information'] = 'addon.xml';
$Configuration['Update']['Remote']['RPC']['Download'] = 'get';