<?php if (!defined('APPLICATION')) exit();
// DO NOT EDIT THIS FILE
// All of the settings defined here can be overridden in the /conf/config.php file.

$Configuration['Conversations']['Installed'] = '0';
$Configuration['Conversations']['Conversations']['PerPage'] = '50';
$Configuration['Conversations']['Messages']['PerPage']      = '50';
$Configuration['Conversations']['Message']['MaxLength']     = '2000';
$Configuration['Conversations']['Message']['Format']        = 'Text';