<?php return [
    'name' => 'Riceball Emoticons',
    'author' => 'David Lanham',
    'description' => 'A uniquely cute set of emoticons modelled to look like little balls of rice. Check out <a href="http://dlanham.com" target="_blank">dlanham.com</a> for more of the author\'s stuff.',
    'format' => '<img class="emoji" src="{src}" title="{name}" alt="{name}" srcset="{dir}/{basename}@2x{ext} 2x" />',
    'icon' => 'rice-icon.png',
    'emoji' =>
        [
            -1 => '-1.png',
            '+1' => '+1.png',
            'angry' => 'angry.png',
            'blush' => 'blush.png',
            'chuffed' => 'chuffed.png',
            'crazy' => 'crazy.png',
            'cry' => 'cry.png',
            'dizzy' => 'dizzy.png',
            'eh' => 'eh.png',
            'fearful' => 'fearful.png',
            'frown' => 'frown.png',
            'glasses' => 'glasses.png',
            'innocent' => 'innocent.png',
            'kiss' => 'kiss.png',
            'lol' => 'lol.png',
            'love' => 'love.png',
            'money' => 'money.png',
            'naughty' => 'naughty.png',
            'neutral' => 'neutral.png',
            'ohnoes' => 'ohnoes.png',
            'pirate' => 'pirate.png',
            'rage' => 'rage.png',
            'sarcastic' => 'sarcastic.png',
            'scream' => 'scream.png',
            'sick' => 'sick.png',
            'silenced' => 'silenced.png',
            'smile' => 'smile.png',
            'sunglasses' => 'sunglasses.png',
            'sweat' => 'sweat.png',
            'tongue' => 'tongue.png',
            'unamused' => 'unamused.png',
            'wink' => 'wink.png',
            'yum' => 'yum.png',
        ],
    'aliases' =>
        [
            ':)' => 'smile',
            ':(' => 'frown',
            ';)' => 'wink',
            ':p' => 'tongue',
            ':\'(' => 'cry',
            ':|' => 'neutral',
            'B)' => 'sunglasses',
            'o:)' => 'innocent',
            'o.O' => 'eh',
            '8-)' => 'glasses',
            '>_<' => 'rage',
            ':3' => 'blush',
        ],
    'editor' =>
        [
            ':)' => 'smile',
            ':(' => 'frown',
            ';)' => 'wink',
            ':p' => 'tongue',
            ':\'(' => 'cry',
            ':|' => 'neutral',
            '8-)' => 'glasses',
            '>_<' => 'rage',
        ],
    'archive' =>
        [
            'dizzy_face' => 'dizzy.png',
            'heart_eyes' => 'love.png',
            'neutral_face' => 'neutral.png',
            'smiling_imp' => 'naughty.png',
            'stuck_out_tongue' => 'tongue.png',
        ],
    'minSize' =>
        [
            'w' => 18,
            'h' => 18,
        ],
    'maxSize' =>
        [
            'w' => 30,
            'h' => 19,
        ],
    'sizes' =>
        [
            0 => 1,
            1 => 2,
        ],
];
