<?php if (!defined('APPLICATION')) exit();
/** This file was generated by the Locale Developer plugin on 2010-11-23 12:23:07 **/

$LocaleInfo['Japanese'] = array (
  'Locale' => 'ja-JP',
  'Name' => 'Japanese Locale',
  'Description' => '日本語 言語ファイルです。',
  'Version' => '1.0',
  'Author' => 'YU-TANG',
  'AuthorEmail' => '0011solo@gmail.com',
  'AuthorUrl' => 'http://www.f3.dion.ne.jp/~element/msaccess/',
  'License' => 'GPL2',
);